import {
  ArrowLeftRight,
  AudioLines,
  Briefcase,
  Calculator,
  Calendar,
  Clapperboard,
  Code2,
  Database,
  Dices,
  FileText,
  Folder,
  Globe,
  GraduationCap,
  HeartPulse,
  Image,
  MessageSquare,
  Palette,
  QrCode,
  Search,
  Share2,
  Shield,
  Smartphone,
  Sparkles,
  Timer,
  Type,
  Video,
  Wand2,
  PartyPopper, Heart, Gamepad2, Camera, Plane, Utensils, BriefcaseBusiness, ShoppingCart, Accessibility, PanelsTopLeft, Megaphone, Radio, MessageCircle, UserRound,
  Wrench,
  type LucideIcon,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  ArrowLeftRight,
  AudioLines,
  Briefcase,
  Calculator,
  Calendar,
  Clapperboard,
  Code2,
  Database,
  Dices,
  FileText,
  Folder,
  Globe,
  GraduationCap,
  HeartPulse,
  Image,
  MessageSquare,
  Palette,
  QrCode,
  Search,
  Share2,
  Shield,
  Smartphone,
  Sparkles,
  Timer,
  Type,
  Video,
  Wand2,
  PartyPopper, Heart, Gamepad2, Camera, Plane, Utensils, BriefcaseBusiness, ShoppingCart, Accessibility, PanelsTopLeft, Megaphone, Radio, MessageCircle, UserRound,
  Wrench,
};

export function toolIcon(name: string): LucideIcon {
  return MAP[name] ?? Wrench;
}
