const ADJ = ["bright","calm","clever","crisp","fair","gentle","keen","lucky","noble","quick","rapid","silent","solar","steady","swift","vivid","wild","zen","amber","coral"];
const NOUN = ["harbor","nexus","pebble","ridge","cedar","atlas","ember","willow","quartz","meadow","orbit","lantern","harbor","finch","cinder","grove","marble","pine","river","summit"];
const FIRST = ["Amina","Jonah","Priya","Luca","Mei","Omar","Sofia","Noah","Elena","Kai","Hana","Diego","Leila","Mateo","Iris","Samir","Freya","Arjun","Nora","Theo"];
const LAST = ["Okoye","Berg","Nakamura","Silva","Kowalski","Hassan","Nguyen","Patel","Costa","Ibrahim","Novak","Andersen","Garcia","Rahman","Petrov"];
const CITIES = ["Lisbon","Nairobi","Osaka","Recife","Bergen","Hanoi","Accra","Valparaíso","Kraków","Muscat","Durban","Tbilisi","Cusco","Tallinn","Busan"];
const COUNTRIES = ["Japan","Kenya","Portugal","Canada","Brazil","Norway","Ghana","Chile","Poland","Oman","Georgia","Peru","Estonia","South Korea","Morocco"];
const WORDS = ["anchor","bramble","canvas","drift","echo","fjord","glimmer","harvest","inlet","jasper","kettle","lagoon","mirror","nectar","olive","plover","quarry","ripple","saffron","timber"];
const FANTASY = ["Aerindel","Brynth","Caelora","Dravok","Elyndra","Faelith","Grommak","Hyral","Ithriel","Jorvask"];

function rnd(n: number) {
  const buf = new Uint32Array(1);
  crypto.getRandomValues(buf);
  return buf[0]! % n;
}
function pick<T>(arr: T[]): T {
  return arr[rnd(arr.length)]!;
}
function bytes(n: number) {
  const b = new Uint8Array(n);
  crypto.getRandomValues(b);
  return b;
}
function hex(n: number) {
  return [...bytes(n)].map((x) => x.toString(16).padStart(2, "0")).join("");
}
function token(n: number) {
  const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
  const b = bytes(n);
  return [...b].map((x) => alphabet[x % alphabet.length]).join("");
}
function uuid() {
  const b = bytes(16);
  b[6] = (b[6]! & 0x0f) | 0x40;
  b[8] = (b[8]! & 0x3f) | 0x80;
  const h = [...b].map((x) => x.toString(16).padStart(2, "0")).join("");
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-${h.slice(12, 16)}-${h.slice(16, 20)}-${h.slice(20)}`;
}
function num(opts: Record<string, string>, key: string, fallback: number) {
  const v = Number(opts[key]);
  return Number.isFinite(v) && v > 0 ? Math.min(500, Math.floor(v)) : fallback;
}
function linesOf(s: string) {
  return s.split(/\n/).map((x) => x.trim()).filter(Boolean);
}

const LOREM =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor.";

export function runGenerator(op: string, opts: Record<string, string>): string {
  const count = num(opts, "count", 8);
  const seed = (opts.seed || opts.keyword || opts.name || "nova").trim() || "nova";
  switch (op) {
    case "lorem": {
      const unit = opts.unit || "paragraphs";
      if (unit === "words") return Array.from({ length: count }, () => pick(WORDS)).join(" ");
      if (unit === "sentences") return Array.from({ length: count }, () => LOREM.split(". ")[0] + ".").join(" ");
      return Array.from({ length: count }, () => LOREM).join("\n\n");
    }
    case "dummy-json":
    case "dummyjson":
    case "dummy-users":
      return JSON.stringify(
        Array.from({ length: count }, (_, i) => ({
          id: uuid(),
          name: `${pick(FIRST)} ${pick(LAST)}`,
          email: `user${i + 1}@example.com`,
          city: pick(CITIES),
        })),
        null,
        2,
      );
    case "dummy-products":
      return JSON.stringify(
        Array.from({ length: count }, (_, i) => ({
          sku: `${(opts.prefix || "SKU").toUpperCase()}-${1000 + i}`,
          name: `${pick(ADJ)} ${pick(NOUN)}`,
          price: 9 + rnd(90),
        })),
        null,
        2,
      );
    case "dummy-csv": {
      const rows = ["name,email,city", ...Array.from({ length: count }, () => `${pick(FIRST)} ${pick(LAST)},${pick(FIRST).toLowerCase()}@example.com,${pick(CITIES)}`)];
      return "// Fictional test data generated by enV\n" + rows.join("\n");
    }
    case "dummy-sql": {
      const rows = Array.from({ length: count }, (_, i) => `INSERT INTO users (id, name, email) VALUES (${i + 1}, '${pick(FIRST)} ${pick(LAST)}', 'user${i + 1}@example.com');`);
      return "-- Fictional test data generated by enV\n" + rows.join("\n");
    }
    case "passphrase":
      return Array.from({ length: num(opts, "words", 6) }, () => pick(WORDS)).join("-");
    case "random-string":
      return token(num(opts, "length", 16));
    case "random-hex":
      return hex(num(opts, "length", 16));
    case "secure-token":
      return token(num(opts, "length", 32));
    case "random-number": {
      const min = Number(opts.min ?? 1);
      const max = Number(opts.max ?? 100);
      const n = num(opts, "count", 1);
      const lo = Math.min(min, max);
      const hi = Math.max(min, max);
      return Array.from({ length: n }, () => lo + rnd(hi - lo + 1)).join("\n");
    }
    case "random-name":
    case "test-names":
      return Array.from({ length: count }, () => `${pick(FIRST)} ${pick(LAST)}`).join("\n");
    case "username":
    case "gamer-name":
      return Array.from({ length: count }, () => `${pick(ADJ)}${pick(NOUN)}${rnd(99)}`).join("\n");
    case "country":
      return Array.from({ length: count }, () => pick(COUNTRIES)).join("\n");
    case "city":
      return Array.from({ length: count }, () => pick(CITIES)).join("\n");
    case "rand-color":
      return Array.from({ length: count }, () => `#${hex(3)}`).join("\n");
    case "word":
      return Array.from({ length: count }, () => pick(WORDS)).join("\n");
    case "rand-date":
      return Array.from({ length: count }, () => {
        const y = 1990 + rnd(35);
        const m = 1 + rnd(12);
        const d = 1 + rnd(28);
        return `${y}-${String(m).padStart(2, "0")}-${String(d).padStart(2, "0")}`;
      }).join("\n");
    case "yesno":
      return rnd(2) === 0 ? "Yes" : "No";
    case "decision": {
      const options = linesOf(opts.options || opts.names || "");
      if (options.length < 2) throw new Error("Enter at least two options, one per line.");
      return pick(options);
    }
    case "teams": {
      const names = linesOf(opts.names || "");
      const k = num(opts, "teams", 2);
      if (names.length < k) throw new Error("Need at least as many names as teams.");
      const shuffled = [...names];
      for (let i = shuffled.length - 1; i > 0; i--) {
        const j = rnd(i + 1);
        [shuffled[i], shuffled[j]] = [shuffled[j]!, shuffled[i]!];
      }
      const teams: string[][] = Array.from({ length: k }, () => []);
      shuffled.forEach((n, i) => teams[i % k]!.push(n));
      return teams.map((t, i) => `Team ${i + 1}\n${t.join("\n")}`).join("\n\n");
    }
    case "secret-santa": {
      const names = linesOf(opts.names || "");
      if (names.length < 2) throw new Error("Enter at least two names.");
      const recv = [...names];
      for (let attempt = 0; attempt < 40; attempt++) {
        for (let i = recv.length - 1; i > 0; i--) {
          const j = rnd(i + 1);
          [recv[i], recv[j]] = [recv[j]!, recv[i]!];
        }
        if (recv.every((r, i) => r !== names[i])) {
          return names.map((n, i) => `${n} → ${recv[i]}`).join("\n");
        }
      }
      throw new Error("Could not build a derangement. Add more names.");
    }
    case "fantasy-name":
      return Array.from({ length: count }, () => pick(FANTASY) + pick(["iel","or","eth","an","is"])).join("\n");
    case "nickname":
      return Array.from({ length: count }, () => `${seed.slice(0, 3)}${pick(ADJ)}`).join("\n");
    case "pet-name":
      return Array.from({ length: count }, () => pick(["Miso","Pebble","Nimbus","Fig","Clover","Sable","Pip","Maple"])).join("\n");
    case "baby-name":
      return Array.from({ length: count }, () => pick(FIRST)).join("\n");
    case "story-prompt":
    case "writing-prompt":
      return `${pick(FIRST)} must ${pick(["return","protect","invent","abandon"])} a ${pick(NOUN)} before ${pick(["dawn","winter","the tide","the trial"])}.`;
    case "plot":
      return `Character: ${pick(FIRST)}\nWant: a ${pick(NOUN)}\nObstacle: a ${pick(ADJ)} ${pick(NOUN)}`;
    case "biz-name":
    case "company-name":
    case "brand-name":
    case "product-name":
      return Array.from({ length: count }, () => `${pick(ADJ)} ${seed}`).join("\n");
    case "sku": {
      const prefix = (opts.prefix || "SKU").toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 8) || "SKU";
      return Array.from({ length: count }, (_, i) => `${prefix}-${hex(3).toUpperCase()}${i}`).join("\n");
    }
    case "hashtags":
      return seed
        .split(/\s+/)
        .filter(Boolean)
        .flatMap((w) => [`#${w}`, `#${w}tips`, `#${pick(ADJ)}${w}`])
        .join(" ");
    case "uuid-list":
      return Array.from({ length: count }, () => uuid()).join("\n");
    case "test-address":
      return Array.from({ length: count }, () => `${100 + rnd(900)} ${pick(NOUN).replace(/^./, (c) => c.toUpperCase())} Street, ${pick(CITIES)}`).join("\n");
    case "test-email":
      return Array.from({ length: count }, (_, i) => `${pick(FIRST).toLowerCase()}.${pick(LAST).toLowerCase()}${i}@example.com`).join("\n");
    case "test-phone":
      return Array.from({ length: count }, () => `+1-555-01${String(rnd(100)).padStart(2, "0")}`).join("\n");
    default:
      throw new Error("Unknown generator.");
  }
}
