const ADJ = ["bright","calm","clever","crisp","fair","gentle","keen","lucky","noble","quick","rapid","silent","solar","steady","swift","vivid","wild","zen","amber","coral"];
const NOUN = ["harbor","nexus","pebble","ridge","cedar","atlas","ember","willow","quartz","meadow","orbit","lantern","harbor","finch","cinder","grove","marble","pine","river","summit"];
const FIRST = ["Amina","Jonah","Priya","Luca","Mei","Omar","Sofia","Noah","Elena","Kai","Hana","Diego","Leila","Mateo","Iris","Samir","Freya","Arjun","Nora","Theo"];
const LAST = ["Okoye","Berg","Nakamura","Silva","Kowalski","Hassan","Nguyen","Patel","Costa","Ibrahim","Novak","Andersen","Garcia","Rahman","Petrov"];
const CITIES = ["Lisbon","Nairobi","Osaka","Recife","Bergen","Hanoi","Accra","Valparaíso","Kraków","Muscat","Durban","Tbilisi","Cusco","Tallinn","Busan"];
const COUNTRIES = ["Japan","Kenya","Portugal","Canada","Brazil","Norway","Ghana","Chile","Poland","Oman","Georgia","Peru","Estonia","South Korea","Morocco"];
const WORDS = ["anchor","bramble","canvas","drift","echo","fjord","glimmer","harvest","inlet","jasper","kettle","lagoon","mirror","nectar","olive","plover","quarry","ripple","saffron","timber"];
const FANTASY = ["Aerindel","Brynth","Caelora","Dravok","Elyndra","Faelith","Grommak","Hyral","Ithriel","Jorvask"];

function rnd(n: number) {
  const buf = new Uint32Array(1);
  crypto.getRandomValues(buf);
  return buf[0]! % n;
}
function pick<T>(arr: T[]): T {
  return arr[rnd(arr.length)]!;
}
function bytes(n: number) {
  const b = new Uint8Array(n);
  crypto.getRandomValues(b);
  return b;
}
function hex(n: number) {
  return [...bytes(n)].map((x) => x.toString(16).padStart(2, "0")).join("");
}
function token(n: number) {
  const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
  const b = bytes(n);
  return [...b].map((x) => alphabet[x % alphabet.length]).join("");
}
function uuid() {
  const b = bytes(16);
  b[6] = (b[6]! & 0x0f) | 0x40;
  b[8] = (b[8]! & 0x3f) | 0x80;
  const h = [...b].map((x) => x.toString(16).padStart(2, "0")).join("");
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-${h.slice(12, 16)}-${h.slice(16, 20)}-${h.slice(20)}`;
}
function num(opts: Record<string, string>, key: string, fallback: number) {
  const v = Number(opts[key]);
  return Number.isFinite(v) && v > 0 ? Math.min(500, Math.floor(v)) : fallback;
}
function linesOf(s: string) {
  return s.split(/\n/).map((x) => x.trim()).filter(Boolean);
}
function uniquePicks<T>(arr: T[], count: number): T[] {
  const pool = [...arr];
  const out: T[] = [];
  while (pool.length && out.length < count) {
    const i = rnd(pool.length);
    out.push(pool.splice(i, 1)[0]!);
  }
  return out;
}

function optionList(opts: Record<string, string>) {
  return linesOf(opts.options || opts.items || opts.names || opts.values || "");
}


const LOREM =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor.";

export function runGenerator(op: string, opts: Record<string, string>): string {
  const count = num(opts, "count", 8);
  const seed = (opts.seed || opts.keyword || opts.name || "nova").trim() || "nova";
  switch (op) {
    case "lorem": {
      const unit = opts.unit || "paragraphs";
      if (unit === "words") return Array.from({ length: count }, () => pick(WORDS)).join(" ");
      if (unit === "sentences") return Array.from({ length: count }, () => LOREM.split(". ")[0] + ".").join(" ");
      return Array.from({ length: count }, () => LOREM).join("\n\n");
    }
    case "dummy-json":
    case "dummyjson":
    case "dummy-users":
      return JSON.stringify(
        Array.from({ length: count }, (_, i) => ({
          id: uuid(),
          name: `${pick(FIRST)} ${pick(LAST)}`,
          email: `user${i + 1}@example.com`,
          city: pick(CITIES),
        })),
        null,
        2,
      );
    case "dummy-products":
      return JSON.stringify(
        Array.from({ length: count }, (_, i) => ({
          sku: `${(opts.prefix || "SKU").toUpperCase()}-${1000 + i}`,
          name: `${pick(ADJ)} ${pick(NOUN)}`,
          price: 9 + rnd(90),
        })),
        null,
        2,
      );
    case "dummy-csv": {
      const rows = ["name,email,city", ...Array.from({ length: count }, () => `${pick(FIRST)} ${pick(LAST)},${pick(FIRST).toLowerCase()}@example.com,${pick(CITIES)}`)];
      return rows.join("\n");
    }
    case "dummy-sql": {
      const rows = Array.from({ length: count }, (_, i) => `INSERT INTO users (id, name, email) VALUES (${i + 1}, '${pick(FIRST)} ${pick(LAST)}', 'user${i + 1}@example.com');`);
      return "-- Fictional test data generated by enV\n" + rows.join("\n");
    }
    case "passphrase":
      return Array.from({ length: num(opts, "words", 6) }, () => pick(WORDS)).join("-");
    case "random-string":
      return token(num(opts, "length", 16));
    case "random-hex":
      return hex(num(opts, "length", 16));
    case "secure-token":
      return token(num(opts, "length", 32));
    case "random-number": {
      const min = Number(opts.min ?? 1);
      const max = Number(opts.max ?? 100);
      const n = num(opts, "count", 1);
      const lo = Math.min(min, max);
      const hi = Math.max(min, max);
      return Array.from({ length: n }, () => lo + rnd(hi - lo + 1)).join("\n");
    }
    case "random-name":
    case "test-names":
      return Array.from({ length: count }, () => `${pick(FIRST)} ${pick(LAST)}`).join("\n");
    case "username":
    case "gamer-name":
      return Array.from({ length: count }, () => `${pick(ADJ)}${pick(NOUN)}${rnd(99)}`).join("\n");
    case "country":
      return Array.from({ length: count }, () => pick(COUNTRIES)).join("\n");
    case "city":
      return Array.from({ length: count }, () => pick(CITIES)).join("\n");
    case "rand-color":
      return Array.from({ length: count }, () => `#${hex(3)}`).join("\n");
    case "word":
      return Array.from({ length: count }, () => pick(WORDS)).join("\n");
    case "rand-date":
      return Array.from({ length: count }, () => {
        const y = 1990 + rnd(35);
        const m = 1 + rnd(12);
        const d = 1 + rnd(28);
        return `${y}-${String(m).padStart(2, "0")}-${String(d).padStart(2, "0")}`;
      }).join("\n");
    case "yesno":
      return rnd(2) === 0 ? "Yes" : "No";
    case "decision": {
      const options = linesOf(opts.options || opts.names || "");
      if (options.length < 2) throw new Error("Enter at least two options, one per line.");
      return pick(options);
    }
    case "teams": {
      const names = linesOf(opts.names || "");
      const k = num(opts, "teams", 2);
      if (names.length < k) throw new Error("Need at least as many names as teams.");
      const shuffled = [...names];
      for (let i = shuffled.length - 1; i > 0; i--) {
        const j = rnd(i + 1);
        [shuffled[i], shuffled[j]] = [shuffled[j]!, shuffled[i]!];
      }
      const teams: string[][] = Array.from({ length: k }, () => []);
      shuffled.forEach((n, i) => teams[i % k]!.push(n));
      return teams.map((t, i) => `Team ${i + 1}\n${t.join("\n")}`).join("\n\n");
    }
    case "secret-santa": {
      const names = linesOf(opts.names || "");
      if (names.length < 2) throw new Error("Enter at least two names.");
      const recv = [...names];
      for (let attempt = 0; attempt < 40; attempt++) {
        for (let i = recv.length - 1; i > 0; i--) {
          const j = rnd(i + 1);
          [recv[i], recv[j]] = [recv[j]!, recv[i]!];
        }
        if (recv.every((r, i) => r !== names[i])) {
          return names.map((n, i) => `${n} → ${recv[i]}`).join("\n");
        }
      }
      throw new Error("Could not build a derangement. Add more names.");
    }
    case "fantasy-name":
      return Array.from({ length: count }, () => pick(FANTASY) + pick(["iel","or","eth","an","is"])).join("\n");
    case "nickname":
      return Array.from({ length: count }, () => `${seed.slice(0, 3)}${pick(ADJ)}`).join("\n");
    case "pet-name":
      return Array.from({ length: count }, () => pick(["Miso","Pebble","Nimbus","Fig","Clover","Sable","Pip","Maple"])).join("\n");
    case "baby-name":
      return Array.from({ length: count }, () => pick(FIRST)).join("\n");
    case "story-prompt":
    case "writing-prompt":
      return `${pick(FIRST)} must ${pick(["return","protect","invent","abandon"])} a ${pick(NOUN)} before ${pick(["dawn","winter","the tide","the trial"])}.`;
    case "plot":
      return `Character: ${pick(FIRST)}\nWant: a ${pick(NOUN)}\nObstacle: a ${pick(ADJ)} ${pick(NOUN)}`;
    case "biz-name":
    case "company-name":
    case "brand-name":
    case "product-name":
      return Array.from({ length: count }, () => `${pick(ADJ)} ${seed}`).join("\n");
    case "sku": {
      const prefix = (opts.prefix || "SKU").toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 8) || "SKU";
      return Array.from({ length: count }, (_, i) => `${prefix}-${hex(3).toUpperCase()}${i}`).join("\n");
    }
    case "hashtags":
      return seed
        .split(/\s+/)
        .filter(Boolean)
        .flatMap((w) => [`#${w}`, `#${w}tips`, `#${pick(ADJ)}${w}`])
        .join(" ");
    case "uuid-list":
      return Array.from({ length: count }, () => uuid()).join("\n");
    case "coin-flip":
      return rnd(2) === 0 ? "Heads" : "Tails";
    case "dice-roller": {
      const dice = Math.max(1, Math.min(100, Math.floor(Number(opts.dice || 1))));
      const sides = Math.max(2, Math.min(1000, Math.floor(Number(opts.sides || 6))));
      const rolls = Array.from({ length: dice }, () => 1 + rnd(sides));
      return `${dice}d${sides}: ${rolls.join(", ")}\nTotal: ${rolls.reduce((a, b) => a + b, 0)}`;
    }
    case "wheel": {
      const options = optionList(opts);
      if (options.length < 2) throw new Error("Enter at least two options, one per line.");
      return `Selected: ${pick(options)}`;
    }
    case "name-generator":
    case "name-picker":
    case "name-randomizer":
    case "name-wheel":
    case "name-list-generator":
      return Array.from({ length: op.endsWith("list-generator") ? count : 1 }, () => `${pick(FIRST)} ${pick(LAST)}`).join("\n");
    case "username-picker":
    case "username-randomizer":
    case "username-wheel":
    case "username-list-generator":
      return Array.from({ length: op.endsWith("list-generator") ? count : 1 }, () => `${pick(ADJ)}${pick(NOUN)}${rnd(100)}`).join("\n");
    case "country-picker":
    case "country-randomizer":
    case "country-wheel":
    case "country-list-generator":
      return (op.endsWith("list-generator") ? uniquePicks(COUNTRIES, Math.min(count, COUNTRIES.length)) : [pick(COUNTRIES)]).join("\n");
    case "city-picker":
    case "city-randomizer":
    case "city-wheel":
    case "city-list-generator":
      return (op.endsWith("list-generator") ? uniquePicks(CITIES, Math.min(count, CITIES.length)) : [pick(CITIES)]).join("\n");
    case "color-randomizer":
    case "color-wheel":
    case "color-list-generator":
      return Array.from({ length: op.endsWith("list-generator") ? count : 1 }, () => `#${hex(3)}`).join("\n");
    case "word-generator":
    case "word-picker":
    case "word-randomizer":
    case "word-wheel":
    case "word-list-generator":
      return Array.from({ length: op.endsWith("list-generator") ? count : 1 }, () => pick(WORDS)).join("\n");
    case "emoji-generator":
    case "emoji-picker":
    case "emoji-randomizer":
    case "emoji-wheel":
    case "emoji-list-generator": {
      const emojis = ["😀","😂","😍","🤔","🔥","🎉","🚀","❤️","⭐","🌍","🎵","🎮","🍕","☀️","🌈"];
      return Array.from({ length: op.endsWith("list-generator") ? count : 1 }, () => pick(emojis)).join(" ");
    }
    case "date-generator":
    case "date-picker":
    case "date-randomizer":
    case "date-wheel":
    case "date-list-generator":
      return Array.from({ length: op.endsWith("list-generator") ? count : 1 }, () => { const y=1990+rnd(36), m=1+rnd(12), d=1+rnd(28); return `${y}-${String(m).padStart(2,"0")}-${String(d).padStart(2,"0")}`; }).join("\n");
    case "time-generator":
    case "time-picker":
    case "time-randomizer":
    case "time-wheel":
    case "time-list-generator":
      return Array.from({ length: op.endsWith("list-generator") ? count : 1 }, () => `${String(rnd(24)).padStart(2,"0")}:${String(rnd(60)).padStart(2,"0")}`).join("\n");
    case "number-generator":
    case "number-picker":
    case "number-randomizer":
    case "number-wheel":
    case "number-list-generator":
      return Array.from({ length: op.endsWith("list-generator") ? count : 1 }, () => String(rnd(1000))).join("\n");
    case "decision-generator":
    case "decision-picker":
    case "decision-randomizer":
    case "decision-wheel":
    case "decision-list-generator": {
      const options = optionList(opts);
      if (options.length < 2) throw new Error("Enter at least two options, one per line.");
      if (op.endsWith("list-generator")) return uniquePicks(options, options.length).join("\n");
      return pick(options);
    }
    case "team-picker":
    case "team-randomizer":
    case "team-wheel":
    case "team-list-generator": {
      const names = optionList(opts);
      if (!names.length) throw new Error("Enter names, one per line.");
      return pick(names);
    }
    case "group-generator":
    case "group-picker":
    case "group-randomizer":
    case "group-wheel":
    case "group-list-generator": {
      const names = optionList(opts);
      if (!names.length) throw new Error("Enter names, one per line.");
      const groups = Math.max(2, Math.min(names.length, Math.floor(Number(opts.groups || 2))));
      const shuffled = uniquePicks(names, names.length);
      const buckets = Array.from({length: groups}, () => [] as string[]);
      shuffled.forEach((n,i)=>buckets[i%groups]!.push(n));
      return buckets.map((b,i)=>`Group ${i+1}\n${b.join("\n")}`).join("\n\n");
    }
    case "secret-santa-picker":
    case "secret-santa-randomizer":
    case "secret-santa-wheel":
    case "secret-santa-list-generator":
      return runGenerator("secret-santa", opts);
    case "story-generator":
    case "story-picker":
    case "story-randomizer":
    case "story-wheel":
    case "story-list-generator":
      return Array.from({length: op.endsWith("list-generator") ? count : 1}, () => `Story seed: ${pick(FIRST)} discovers a ${pick(NOUN)} that could change everything.`).join("\n");
    case "character-generator":
    case "character-picker":
    case "character-randomizer":
    case "character-wheel":
    case "character-list-generator":
      return Array.from({length: op.endsWith("list-generator") ? count : 1}, () => `${pick(FIRST)} — ${pick(ADJ)} ${pick(["explorer","inventor","guardian","scholar","rogue"])}`).join("\n");
    case "fantasy-generator":
    case "fantasy-picker":
    case "fantasy-randomizer":
    case "fantasy-wheel":
    case "fantasy-list-generator":
      return Array.from({length: op.endsWith("list-generator") ? count : 1}, () => pick(FANTASY)+pick(["iel","or","eth","an","is"])).join("\n");
    case "gamer-generator":
    case "gamer-picker":
    case "gamer-randomizer":
    case "gamer-wheel":
    case "gamer-list-generator":
      return Array.from({length: op.endsWith("list-generator") ? count : 1}, () => `${pick(ADJ)}${pick(NOUN)}${rnd(999)}`).join("\n");
    case "pet-generator":
    case "pet-picker":
    case "pet-randomizer":
    case "pet-wheel":
    case "pet-list-generator":
      return Array.from({length: op.endsWith("list-generator") ? count : 1}, () => pick(["Miso","Pebble","Nimbus","Fig","Clover","Sable","Pip","Maple"])).join("\n");
    case "baby-generator":
    case "baby-picker":
    case "baby-randomizer":
    case "baby-wheel":
    case "baby-list-generator":
      return Array.from({length: op.endsWith("list-generator") ? count : 1}, () => pick(FIRST)).join("\n");
    case "test-address":
      return Array.from({ length: count }, () => `${100 + rnd(900)} ${pick(NOUN).replace(/^./, (c) => c.toUpperCase())} Street, ${pick(CITIES)}`).join("\n");
    case "test-email":
      return Array.from({ length: count }, (_, i) => `${pick(FIRST).toLowerCase()}.${pick(LAST).toLowerCase()}${i}@example.com`).join("\n");
    case "test-phone":
      return Array.from({ length: count }, () => `+1-555-01${String(rnd(100)).padStart(2, "0")}`).join("\n");
    default:
      throw new Error("Unknown generator.");
  }
}
