import type { CalculatorDef, CalcOutput, Field } from "./formulas";
import mathExpansion from "@/data/math-expansion.json";

const f = (name: string, label: string, extra: Partial<Field> = {}): Field => ({ name, label, type: "number", ...extra });
const n = (v: Record<string,string>, key: string): number => {
  const x = Number(String(v[key] ?? "").replace(/,/g, "").trim());
  if (!Number.isFinite(x)) throw new Error(`Enter a valid ${key}.`);
  return x;
};
const out = (label: string, value: number, primary = true, hint?: string): CalcOutput => ({ label, value: Number.isFinite(value) ? String(Number(value.toPrecision(12))) : "Undefined", primary, hint });

type Spec = { key: string; name: string; fields: Field[]; formula: string; solve: Record<string,(v:Record<string,string>)=>number>; labels: Record<string,string> };

// Reusable school/college STEM relationships. Each relationship becomes one
// calculator per unknown, so students can practice rearranging equations as
// well as direct substitution. Every generated calculator is executable.
const specs: Spec[] = [
  { key:"linear", name:"Linear Relation", fields:[f("m","Slope"),f("x","x"),f("b","Intercept"),f("y","y")], formula:"y = mx + b", labels:{m:"Slope",x:"x",b:"Intercept",y:"y"}, solve:{y:v=>n(v,"m")*n(v,"x")+n(v,"b"),m:v=>(n(v,"y")-n(v,"b"))/n(v,"x"),x:v=>(n(v,"y")-n(v,"b"))/n(v,"m"),b:v=>n(v,"y")-n(v,"m")*n(v,"x")} },
  { key:"distance", name:"Distance Rate Time", fields:[f("d","Distance"),f("r","Rate"),f("t","Time")], formula:"d = rt", labels:{d:"Distance",r:"Rate",t:"Time"}, solve:{d:v=>n(v,"r")*n(v,"t"),r:v=>n(v,"d")/n(v,"t"),t:v=>n(v,"d")/n(v,"r")} },
  { key:"acceleration", name:"Acceleration", fields:[f("a","Acceleration"),f("v","Final velocity"),f("u","Initial velocity"),f("t","Time")], formula:"a = (v − u) / t", labels:{a:"Acceleration",v:"Final velocity",u:"Initial velocity",t:"Time"}, solve:{a:v=>(n(v,"v")-n(v,"u"))/n(v,"t"),v:v=>n(v,"u")+n(v,"a")*n(v,"t"),u:v=>n(v,"v")-n(v,"a")*n(v,"t"),t:v=>(n(v,"v")-n(v,"u"))/n(v,"a")} },
  { key:"force", name:"Newton's Second Law", fields:[f("F","Force"),f("m","Mass"),f("a","Acceleration")], formula:"F = ma", labels:{F:"Force",m:"Mass",a:"Acceleration"}, solve:{F:v=>n(v,"m")*n(v,"a"),m:v=>n(v,"F")/n(v,"a"),a:v=>n(v,"F")/n(v,"m")} },
  { key:"work", name:"Mechanical Work", fields:[f("W","Work"),f("F","Force"),f("d","Distance")], formula:"W = Fd", labels:{W:"Work",F:"Force",d:"Distance"}, solve:{W:v=>n(v,"F")*n(v,"d"),F:v=>n(v,"W")/n(v,"d"),d:v=>n(v,"W")/n(v,"F")} },
  { key:"power", name:"Mechanical Power", fields:[f("P","Power"),f("W","Work"),f("t","Time")], formula:"P = W/t", labels:{P:"Power",W:"Work",t:"Time"}, solve:{P:v=>n(v,"W")/n(v,"t"),W:v=>n(v,"P")*n(v,"t"),t:v=>n(v,"W")/n(v,"P")} },
  { key:"ke", name:"Kinetic Energy", fields:[f("E","Kinetic energy"),f("m","Mass"),f("v","Velocity")], formula:"E = ½mv²", labels:{E:"Kinetic energy",m:"Mass",v:"Velocity"}, solve:{E:v=>.5*n(v,"m")*n(v,"v")**2,m:v=>2*n(v,"E")/n(v,"v")**2,v:v=>Math.sqrt(2*n(v,"E")/n(v,"m"))} },
  { key:"pe", name:"Gravitational Potential Energy", fields:[f("E","Potential energy"),f("m","Mass"),f("g","Gravity"),f("h","Height")], formula:"E = mgh", labels:{E:"Potential energy",m:"Mass",g:"Gravity",h:"Height"}, solve:{E:v=>n(v,"m")*n(v,"g")*n(v,"h"),m:v=>n(v,"E")/(n(v,"g")*n(v,"h")),g:v=>n(v,"E")/(n(v,"m")*n(v,"h")),h:v=>n(v,"E")/(n(v,"m")*n(v,"g"))} },
  { key:"density", name:"Density", fields:[f("rho","Density"),f("m","Mass"),f("V","Volume")], formula:"ρ = m/V", labels:{rho:"Density",m:"Mass",V:"Volume"}, solve:{rho:v=>n(v,"m")/n(v,"V"),m:v=>n(v,"rho")*n(v,"V"),V:v=>n(v,"m")/n(v,"rho")} },
  { key:"pressure", name:"Pressure", fields:[f("p","Pressure"),f("F","Force"),f("A","Area")], formula:"p = F/A", labels:{p:"Pressure",F:"Force",A:"Area"}, solve:{p:v=>n(v,"F")/n(v,"A"),F:v=>n(v,"p")*n(v,"A"),A:v=>n(v,"F")/n(v,"p")} },
  { key:"ohm", name:"Ohm's Law", fields:[f("V","Voltage"),f("I","Current"),f("R","Resistance")], formula:"V = IR", labels:{V:"Voltage",I:"Current",R:"Resistance"}, solve:{V:v=>n(v,"I")*n(v,"R"),I:v=>n(v,"V")/n(v,"R"),R:v=>n(v,"V")/n(v,"I")} },
  { key:"electrical-power", name:"Electrical Power", fields:[f("P","Power"),f("V","Voltage"),f("I","Current")], formula:"P = VI", labels:{P:"Power",V:"Voltage",I:"Current"}, solve:{P:v=>n(v,"V")*n(v,"I"),V:v=>n(v,"P")/n(v,"I"),I:v=>n(v,"P")/n(v,"V")} },
  { key:"charge", name:"Electric Charge", fields:[f("Q","Charge"),f("I","Current"),f("t","Time")], formula:"Q = It", labels:{Q:"Charge",I:"Current",t:"Time"}, solve:{Q:v=>n(v,"I")*n(v,"t"),I:v=>n(v,"Q")/n(v,"t"),t:v=>n(v,"Q")/n(v,"I")} },
  { key:"wave-speed", name:"Wave Speed", fields:[f("v","Wave speed"),f("f","Frequency"),f("lambda","Wavelength")], formula:"v = fλ", labels:{v:"Wave speed",f:"Frequency",lambda:"Wavelength"}, solve:{v:v=>n(v,"f")*n(v,"lambda"),f:v=>n(v,"v")/n(v,"lambda"),lambda:v=>n(v,"v")/n(v,"f")} },
  { key:"frequency-period", name:"Frequency and Period", fields:[f("f","Frequency"),f("T","Period")], formula:"f = 1/T", labels:{f:"Frequency",T:"Period"}, solve:{f:v=>1/n(v,"T"),T:v=>1/n(v,"f")} },
  { key:"heat", name:"Heat Energy", fields:[f("Q","Heat energy"),f("m","Mass"),f("c","Specific heat"),f("deltaT","Temperature change")], formula:"Q = mcΔT", labels:{Q:"Heat energy",m:"Mass",c:"Specific heat",deltaT:"Temperature change"}, solve:{Q:v=>n(v,"m")*n(v,"c")*n(v,"deltaT"),m:v=>n(v,"Q")/(n(v,"c")*n(v,"deltaT")),c:v=>n(v,"Q")/(n(v,"m")*n(v,"deltaT")),deltaT:v=>n(v,"Q")/(n(v,"m")*n(v,"c"))} },
  { key:"ideal-gas", name:"Ideal Gas Law", fields:[f("P","Pressure"),f("V","Volume"),f("n","Amount"),f("R","Gas constant"),f("T","Temperature")], formula:"PV = nRT", labels:{P:"Pressure",V:"Volume",n:"Amount",R:"Gas constant",T:"Temperature"}, solve:{P:v=>n(v,"n")*n(v,"R")*n(v,"T")/n(v,"V"),V:v=>n(v,"n")*n(v,"R")*n(v,"T")/n(v,"P"),n:v=>n(v,"P")*n(v,"V")/(n(v,"R")*n(v,"T")),R:v=>n(v,"P")*n(v,"V")/(n(v,"n")*n(v,"T")),T:v=>n(v,"P")*n(v,"V")/(n(v,"n")*n(v,"R"))} },
  { key:"simple-interest", name:"Simple Interest", fields:[f("I","Interest"),f("P","Principal"),f("r","Rate"),f("t","Time")], formula:"I = Prt", labels:{I:"Interest",P:"Principal",r:"Rate",t:"Time"}, solve:{I:v=>n(v,"P")*n(v,"r")*n(v,"t"),P:v=>n(v,"I")/(n(v,"r")*n(v,"t")),r:v=>n(v,"I")/(n(v,"P")*n(v,"t")),t:v=>n(v,"I")/(n(v,"P")*n(v,"r"))} },
  { key:"compound-growth", name:"Compound Growth", fields:[f("A","Final amount"),f("P","Initial amount"),f("r","Rate"),f("n","Periods per year"),f("t","Years")], formula:"A = P(1+r/n)^(nt)", labels:{A:"Final amount",P:"Initial amount",r:"Rate",n:"Periods/year",t:"Years"}, solve:{A:v=>n(v,"P")*(1+n(v,"r")/n(v,"n"))**(n(v,"n")*n(v,"t")),P:v=>n(v,"A")/(1+n(v,"r")/n(v,"n"))**(n(v,"n")*n(v,"t")),r:v=>n(v,"n")*((n(v,"A")/n(v,"P"))**(1/(n(v,"n")*n(v,"t")))-1),t:v=>Math.log(n(v,"A")/n(v,"P"))/(n(v,"n")*Math.log(1+n(v,"r")/n(v,"n")))} },
  { key:"cagr", name:"CAGR", fields:[f("A","Ending value"),f("P","Beginning value"),f("t","Years"),f("cagr","CAGR rate")], formula:"CAGR = (A/P)^(1/t) − 1", labels:{A:"Ending value",P:"Beginning value",t:"Years",cagr:"CAGR rate"}, solve:{A:v=>n(v,"P")*(1+n(v,"cagr"))**n(v,"t"),P:v=>n(v,"A")/(1+n(v,"cagr"))**n(v,"t"),t:v=>Math.log(n(v,"A")/n(v,"P"))/Math.log(1+n(v,"cagr")),cagr:v=>(n(v,"A")/n(v,"P"))**(1/n(v,"t"))-1} },
  { key:"rectangle-area", name:"Rectangle Area", fields:[f("A","Area"),f("l","Length"),f("w","Width")], formula:"A = lw", labels:{A:"Area",l:"Length",w:"Width"}, solve:{A:v=>n(v,"l")*n(v,"w"),l:v=>n(v,"A")/n(v,"w"),w:v=>n(v,"A")/n(v,"l")} },
  { key:"triangle-area", name:"Triangle Area", fields:[f("A","Area"),f("b","Base"),f("h","Height")], formula:"A = bh/2", labels:{A:"Area",b:"Base",h:"Height"}, solve:{A:v=>n(v,"b")*n(v,"h")/2,b:v=>2*n(v,"A")/n(v,"h"),h:v=>2*n(v,"A")/n(v,"b")} },
  { key:"circle-area", name:"Circle Area", fields:[f("A","Area"),f("r","Radius")], formula:"A = πr²", labels:{A:"Area",r:"Radius"}, solve:{A:v=>Math.PI*n(v,"r")**2,r:v=>Math.sqrt(n(v,"A")/Math.PI)} },
  { key:"circle-circumference", name:"Circle Circumference", fields:[f("C","Circumference"),f("r","Radius")], formula:"C = 2πr", labels:{C:"Circumference",r:"Radius"}, solve:{C:v=>2*Math.PI*n(v,"r"),r:v=>n(v,"C")/(2*Math.PI)} },
  { key:"sphere-volume", name:"Sphere Volume", fields:[f("V","Volume"),f("r","Radius")], formula:"V = 4πr³/3", labels:{V:"Volume",r:"Radius"}, solve:{V:v=>4*Math.PI*n(v,"r")**3/3,r:v=>Math.cbrt(3*n(v,"V")/(4*Math.PI))} },
  { key:"cylinder-volume", name:"Cylinder Volume", fields:[f("V","Volume"),f("r","Radius"),f("h","Height")], formula:"V = πr²h", labels:{V:"Volume",r:"Radius",h:"Height"}, solve:{V:v=>Math.PI*n(v,"r")**2*n(v,"h"),r:v=>Math.sqrt(n(v,"V")/(Math.PI*n(v,"h"))),h:v=>n(v,"V")/(Math.PI*n(v,"r")**2)} },
  { key:"cone-volume", name:"Cone Volume", fields:[f("V","Volume"),f("r","Radius"),f("h","Height")], formula:"V = πr²h/3", labels:{V:"Volume",r:"Radius",h:"Height"}, solve:{V:v=>Math.PI*n(v,"r")**2*n(v,"h")/3,r:v=>Math.sqrt(3*n(v,"V")/(Math.PI*n(v,"h"))),h:v=>3*n(v,"V")/(Math.PI*n(v,"r")**2)} },
  { key:"trapezoid-area", name:"Trapezoid Area", fields:[f("A","Area"),f("a","Parallel side a"),f("b","Parallel side b"),f("h","Height")], formula:"A = (a+b)h/2", labels:{A:"Area",a:"Parallel side a",b:"Parallel side b",h:"Height"}, solve:{A:v=>(n(v,"a")+n(v,"b"))*n(v,"h")/2,a:v=>2*n(v,"A")/n(v,"h")-n(v,"b"),b:v=>2*n(v,"A")/n(v,"h")-n(v,"a"),h:v=>2*n(v,"A")/(n(v,"a")+n(v,"b"))} },
  { key:"pythagorean", name:"Pythagorean Theorem", fields:[f("c","Hypotenuse"),f("a","Leg a"),f("b","Leg b")], formula:"c² = a² + b²", labels:{c:"Hypotenuse",a:"Leg a",b:"Leg b"}, solve:{c:v=>Math.hypot(n(v,"a"),n(v,"b")),a:v=>Math.sqrt(n(v,"c")**2-n(v,"b")**2),b:v=>Math.sqrt(n(v,"c")**2-n(v,"a")**2)} },
  { key:"slope", name:"Slope", fields:[f("m","Slope"),f("x1","x₁"),f("y1","y₁"),f("x2","x₂"),f("y2","y₂")], formula:"m = (y₂−y₁)/(x₂−x₁)", labels:{m:"Slope"}, solve:{m:v=>(n(v,"y2")-n(v,"y1"))/(n(v,"x2")-n(v,"x1"))} },
  { key:"distance-coordinate", name:"Coordinate Distance", fields:[f("d","Distance"),f("x1","x₁"),f("y1","y₁"),f("x2","x₂"),f("y2","y₂")], formula:"d = √((x₂−x₁)²+(y₂−y₁)²)", labels:{d:"Distance"}, solve:{d:v=>Math.hypot(n(v,"x2")-n(v,"x1"),n(v,"y2")-n(v,"y1"))} },
  { key:"midpoint-x", name:"Midpoint X", fields:[f("mx","Midpoint x"),f("x1","x₁"),f("x2","x₂")], formula:"mx = (x₁+x₂)/2", labels:{mx:"Midpoint x"}, solve:{mx:v=>(n(v,"x1")+n(v,"x2"))/2} },
  { key:"midpoint-y", name:"Midpoint Y", fields:[f("my","Midpoint y"),f("y1","y₁"),f("y2","y₂")], formula:"my = (y₁+y₂)/2", labels:{my:"Midpoint y"}, solve:{my:v=>(n(v,"y1")+n(v,"y2"))/2} },
  { key:"arithmetic-sequence", name:"Arithmetic Sequence", fields:[f("an","nth term"),f("a1","First term"),f("d","Common difference"),f("n","Term number")], formula:"aₙ = a₁ + (n−1)d", labels:{an:"nth term",a1:"First term",d:"Common difference",n:"Term number"}, solve:{an:v=>n(v,"a1")+(n(v,"n")-1)*n(v,"d"),a1:v=>n(v,"an")-(n(v,"n")-1)*n(v,"d"),d:v=>(n(v,"an")-n(v,"a1"))/(n(v,"n")-1),n:v=>(n(v,"an")-n(v,"a1"))/n(v,"d")+1} },
  { key:"arithmetic-sum", name:"Arithmetic Series Sum", fields:[f("S","Sum"),f("n","Terms"),f("a1","First term"),f("an","Last term")], formula:"S = n(a₁+aₙ)/2", labels:{S:"Sum",n:"Terms",a1:"First term",an:"Last term"}, solve:{S:v=>n(v,"n")*(n(v,"a1")+n(v,"an"))/2,n:v=>2*n(v,"S")/(n(v,"a1")+n(v,"an")),a1:v=>2*n(v,"S")/n(v,"n")-n(v,"an"),an:v=>2*n(v,"S")/n(v,"n")-n(v,"a1")} },
  { key:"geometric-sequence", name:"Geometric Sequence", fields:[f("an","nth term"),f("a1","First term"),f("r","Ratio"),f("n","Term number")], formula:"aₙ = a₁r^(n−1)", labels:{an:"nth term",a1:"First term",r:"Ratio",n:"Term number"}, solve:{an:v=>n(v,"a1")*n(v,"r")**(n(v,"n")-1),a1:v=>n(v,"an")/n(v,"r")**(n(v,"n")-1),r:v=>(n(v,"an")/n(v,"a1"))**(1/(n(v,"n")-1)),n:v=>Math.log(n(v,"an")/n(v,"a1"))/Math.log(n(v,"r"))+1} },
  { key:"geometric-sum", name:"Finite Geometric Sum", fields:[f("S","Sum"),f("a","First term"),f("r","Ratio"),f("n","Terms")], formula:"S = a(rⁿ−1)/(r−1)", labels:{S:"Sum"}, solve:{S:v=>{const r=n(v,"r"),a=n(v,"a"),k=n(v,"n"); return Math.abs(r-1)<1e-12?a*k:a*(r**k-1)/(r-1)}} },
  { key:"simple-average", name:"Weighted Average", fields:[f("x","Value"),f("w","Weight")], formula:"weighted contribution = xw", labels:{x:"Value",w:"Weight"}, solve:{x:v=>n(v,"x")*n(v,"w"),w:v=>n(v,"x")*n(v,"w")} },
  { key:"z-score", name:"Z Score", fields:[f("z","Z score"),f("x","Value"),f("mu","Mean"),f("sigma","Standard deviation")], formula:"z = (x−μ)/σ", labels:{z:"Z score"}, solve:{z:v=>(n(v,"x")-n(v,"mu"))/n(v,"sigma"),x:v=>n(v,"mu")+n(v,"z")*n(v,"sigma"),mu:v=>n(v,"x")-n(v,"z")*n(v,"sigma"),sigma:v=>(n(v,"x")-n(v,"mu"))/n(v,"z")} },
  { key:"variance-population", name:"Population Variance", fields:[f("sigma2","Variance"),f("sumSq","Sum squared deviations"),f("N","Population size")], formula:"σ² = Σ(x−μ)²/N", labels:{sigma2:"Variance",sumSq:"Sum squared deviations",N:"Population size"}, solve:{sigma2:v=>n(v,"sumSq")/n(v,"N"),sumSq:v=>n(v,"sigma2")*n(v,"N"),N:v=>n(v,"sumSq")/n(v,"sigma2")} },
  { key:"standard-error", name:"Standard Error", fields:[f("SE","Standard error"),f("s","Standard deviation"),f("n","Sample size")], formula:"SE = s/√n", labels:{SE:"Standard error",s:"Standard deviation",n:"Sample size"}, solve:{SE:v=>n(v,"s")/Math.sqrt(n(v,"n")),s:v=>n(v,"SE")*Math.sqrt(n(v,"n")),n:v=>(n(v,"s")/n(v,"SE"))**2} },
  { key:"binomial-probability", name:"Binomial Probability", fields:[f("P","Probability"),f("n","Trials"),f("k","Successes"),f("p","Success probability")], formula:"P(X=k)=C(n,k)p^k(1−p)^(n−k)", labels:{P:"Probability"}, solve:{P:v=>{const N=Math.round(n(v,"n")),k=Math.round(n(v,"k")),p=n(v,"p"); let c=1; for(let i=1;i<=k;i++) c*= (N-k+i)/i; return c*p**k*(1-p)**(N-k)}} },
  { key:"percentage-score", name:"Percentage Score", fields:[f("percent","Percent"),f("earned","Points earned"),f("total","Total points")], formula:"percent = earned/total × 100", labels:{percent:"Percentage"}, solve:{percent:v=>n(v,"earned")/n(v,"total")*100,earned:v=>n(v,"percent")/100*n(v,"total"),total:v=>n(v,"earned")/(n(v,"percent")/100)} },
  { key:"unit-price", name:"Unit Price", fields:[f("unit","Unit price"),f("price","Total price"),f("qty","Quantity")], formula:"unit price = price/quantity", labels:{unit:"Unit price"}, solve:{unit:v=>n(v,"price")/n(v,"qty"),price:v=>n(v,"unit")*n(v,"qty"),qty:v=>n(v,"price")/n(v,"unit")} },
  { key:"markup-price", name:"Markup Price", fields:[f("price","Selling price"),f("cost","Cost"),f("markup","Markup rate")], formula:"price = cost(1+markup)", labels:{price:"Selling price"}, solve:{price:v=>n(v,"cost")*(1+n(v,"markup")),cost:v=>n(v,"price")/(1+n(v,"markup")),markup:v=>n(v,"price")/n(v,"cost")-1} },
  { key:"break-even", name:"Break Even", fields:[f("units","Break-even units"),f("fixed","Fixed cost"),f("price","Price/unit"),f("variable","Variable cost/unit")], formula:"units = fixed/(price−variable)", labels:{units:"Break-even units"}, solve:{units:v=>n(v,"fixed")/(n(v,"price")-n(v,"variable"))} },
  { key:"molarity", name:"Molarity", fields:[f("M","Molarity"),f("moles","Moles"),f("V","Volume")], formula:"M = n/V", labels:{M:"Molarity"}, solve:{M:v=>n(v,"moles")/n(v,"V"),moles:v=>n(v,"M")*n(v,"V"),V:v=>n(v,"moles")/n(v,"M")} },
  { key:"moles", name:"Moles from Mass", fields:[f("n","Moles"),f("m","Mass"),f("MM","Molar mass")], formula:"n = m/MM", labels:{n:"Moles"}, solve:{n:v=>n(v,"m")/n(v,"MM"),m:v=>n(v,"n")*n(v,"MM"),MM:v=>n(v,"m")/n(v,"n")} },
  { key:"pH", name:"pH", fields:[f("pH","pH"),f("H","Hydrogen ion concentration")], formula:"pH = −log₁₀[H⁺]", labels:{pH:"pH"}, solve:{pH:v=>-Math.log10(n(v,"H")),H:v=>10**(-n(v,"pH"))} },
  { key:"faraday", name:"Electrical Energy", fields:[f("E","Energy"),f("V","Voltage"),f("Q","Charge")], formula:"E = VQ", labels:{E:"Energy"}, solve:{E:v=>n(v,"V")*n(v,"Q"),V:v=>n(v,"E")/n(v,"Q"),Q:v=>n(v,"E")/n(v,"V")} },
  { key:"torque", name:"Torque", fields:[f("tau","Torque"),f("F","Force"),f("r","Lever arm")], formula:"τ = Fr", labels:{tau:"Torque"}, solve:{tau:v=>n(v,"F")*n(v,"r"),F:v=>n(v,"tau")/n(v,"r"),r:v=>n(v,"tau")/n(v,"F")} },
  { key:"angular-speed", name:"Angular Speed", fields:[f("omega","Angular speed"),f("theta","Angle"),f("t","Time")], formula:"ω = θ/t", labels:{omega:"Angular speed"}, solve:{omega:v=>n(v,"theta")/n(v,"t"),theta:v=>n(v,"omega")*n(v,"t"),t:v=>n(v,"theta")/n(v,"omega")} },
  { key:"centripetal", name:"Centripetal Force", fields:[f("F","Force"),f("m","Mass"),f("v","Speed"),f("r","Radius")], formula:"F = mv²/r", labels:{F:"Centripetal force"}, solve:{F:v=>n(v,"m")*n(v,"v")**2/n(v,"r"),m:v=>n(v,"F")*n(v,"r")/n(v,"v")**2,v:v=>Math.sqrt(n(v,"F")*n(v,"r")/n(v,"m")),r:v=>n(v,"m")*n(v,"v")**2/n(v,"F")} },
  { key:"momentum", name:"Momentum", fields:[f("p","Momentum"),f("m","Mass"),f("v","Velocity")], formula:"p = mv", labels:{p:"Momentum"}, solve:{p:v=>n(v,"m")*n(v,"v"),m:v=>n(v,"p")/n(v,"v"),v:v=>n(v,"p")/n(v,"m")} },
  { key:"impulse", name:"Impulse", fields:[f("J","Impulse"),f("F","Force"),f("dt","Time interval")], formula:"J = FΔt", labels:{J:"Impulse"}, solve:{J:v=>n(v,"F")*n(v,"dt"),F:v=>n(v,"J")/n(v,"dt"),dt:v=>n(v,"J")/n(v,"F")} },
  { key:"spring", name:"Spring Force", fields:[f("F","Force"),f("k","Spring constant"),f("x","Extension")], formula:"F = kx", labels:{F:"Force"}, solve:{F:v=>n(v,"k")*n(v,"x"),k:v=>n(v,"F")/n(v,"x"),x:v=>n(v,"F")/n(v,"k")} },
  { key:"frequency-cycle", name:"Frequency from Cycles", fields:[f("f","Frequency"),f("N","Cycles"),f("t","Time")], formula:"f = N/t", labels:{f:"Frequency"}, solve:{f:v=>n(v,"N")/n(v,"t"),N:v=>n(v,"f")*n(v,"t"),t:v=>n(v,"N")/n(v,"f")} },
  { key:"efficiency", name:"Efficiency", fields:[f("eta","Efficiency"),f("useful","Useful output"),f("input","Input" )], formula:"η = useful/input × 100%", labels:{eta:"Efficiency"}, solve:{eta:v=>n(v,"useful")/n(v,"input")*100,useful:v=>n(v,"eta")/100*n(v,"input"),input:v=>n(v,"useful")/(n(v,"eta")/100)} },
  { key:"power-factor", name:"Power Factor", fields:[f("pf","Power factor"),f("P","Real power"),f("S","Apparent power")], formula:"PF = P/S", labels:{pf:"Power factor"}, solve:{pf:v=>n(v,"P")/n(v,"S"),P:v=>n(v,"pf")*n(v,"S"),S:v=>n(v,"P")/n(v,"pf")} },
  { key:"wavelength", name:"Wavelength", fields:[f("lambda","Wavelength"),f("v","Wave speed"),f("f","Frequency")], formula:"λ = v/f", labels:{lambda:"Wavelength"}, solve:{lambda:v=>n(v,"v")/n(v,"f"),v:v=>n(v,"lambda")*n(v,"f"),f:v=>n(v,"v")/n(v,"lambda")} },
  { key:"lens", name:"Thin Lens", fields:[f("f","Focal length"),f("u","Object distance"),f("v","Image distance")], formula:"1/f = 1/u + 1/v", labels:{f:"Focal length",u:"Object distance",v:"Image distance"}, solve:{f:v=>1/(1/n(v,"u")+1/n(v,"v")),u:v=>1/(1/n(v,"f")-1/n(v,"v")),v:v=>1/(1/n(v,"f")-1/n(v,"u"))} },
  { key:"snell", name:"Snell's Law", fields:[f("n1","Refractive index 1"),f("theta1","Angle 1"),f("n2","Refractive index 2"),f("theta2","Angle 2")], formula:"n₁sinθ₁ = n₂sinθ₂", labels:{n1:"Index 1",theta1:"Angle 1",n2:"Index 2",theta2:"Angle 2"}, solve:{n1:v=>n(v,"n2")*Math.sin(n(v,"theta2")*Math.PI/180)/Math.sin(n(v,"theta1")*Math.PI/180),n2:v=>n(v,"n1")*Math.sin(n(v,"theta1")*Math.PI/180)/Math.sin(n(v,"theta2")*Math.PI/180),theta1:v=>Math.asin(n(v,"n2")*Math.sin(n(v,"theta2")*Math.PI/180)/n(v,"n1"))*180/Math.PI,theta2:v=>Math.asin(n(v,"n1")*Math.sin(n(v,"theta1")*Math.PI/180)/n(v,"n2"))*180/Math.PI} },

    { key:"quadratic-discriminant", name:"Quadratic Discriminant", fields:[f("D","Discriminant"),f("b","Coefficient b"),f("a","Coefficient a"),f("c","Constant c")], formula:"D = b² − 4ac", labels:{D:"Discriminant"}, solve:{D:v=>n(v,"b")**2-4*n(v,"a")*n(v,"c")} },
  { key:"quadratic-root", name:"Quadratic Root", fields:[f("x","Root"),f("a","Coefficient a"),f("b","Coefficient b"),f("c","Coefficient c")], formula:"x = (−b ± √(b²−4ac))/(2a)", labels:{x:"Root"}, solve:{x:v=>(-n(v,"b")+Math.sqrt(n(v,"b")**2-4*n(v,"a")*n(v,"c")))/(2*n(v,"a"))} },
  { key:"vertex-x", name:"Quadratic Vertex X", fields:[f("h","Vertex x"),f("a","Coefficient a"),f("b","Coefficient b")], formula:"h = −b/(2a)", labels:{h:"Vertex x"}, solve:{h:v=>-n(v,"b")/(2*n(v,"a")),b:v=>-2*n(v,"a")*n(v,"h"),a:v=>-n(v,"b")/(2*n(v,"h"))} },
  { key:"vertex-y", name:"Quadratic Vertex Y", fields:[f("k","Vertex y"),f("a","Coefficient a"),f("h","Vertex x"),f("b","Coefficient b"),f("c","Constant c")], formula:"k = ah² + bh + c", labels:{k:"Vertex y"}, solve:{k:v=>n(v,"a")*n(v,"h")**2+n(v,"b")*n(v,"h")+n(v,"c"),c:v=>n(v,"k")-n(v,"a")*n(v,"h")**2-n(v,"b")*n(v,"h"),a:v=>(n(v,"k")-n(v,"b")*n(v,"h")-n(v,"c"))/n(v,"h")**2,b:v=>(n(v,"k")-n(v,"a")*n(v,"h")**2-n(v,"c"))/n(v,"h")} },
  { key:"trig-sine", name:"Sine Ratio", fields:[f("sin","sin θ"),f("opposite","Opposite"),f("hypotenuse","Hypotenuse")], formula:"sin θ = opposite/hypotenuse", labels:{sin:"Sine"}, solve:{sin:v=>n(v,"opposite")/n(v,"hypotenuse"),opposite:v=>n(v,"sin")*n(v,"hypotenuse"),hypotenuse:v=>n(v,"opposite")/n(v,"sin")} },
  { key:"trig-cosine", name:"Cosine Ratio", fields:[f("cos","cos θ"),f("adjacent","Adjacent"),f("hypotenuse","Hypotenuse")], formula:"cos θ = adjacent/hypotenuse", labels:{cos:"Cosine"}, solve:{cos:v=>n(v,"adjacent")/n(v,"hypotenuse"),adjacent:v=>n(v,"cos")*n(v,"hypotenuse"),hypotenuse:v=>n(v,"adjacent")/n(v,"cos")} },
  { key:"trig-tangent", name:"Tangent Ratio", fields:[f("tan","tan θ"),f("opposite","Opposite"),f("adjacent","Adjacent")], formula:"tan θ = opposite/adjacent", labels:{tan:"Tangent"}, solve:{tan:v=>n(v,"opposite")/n(v,"adjacent"),opposite:v=>n(v,"tan")*n(v,"adjacent"),adjacent:v=>n(v,"opposite")/n(v,"tan")} },
  { key:"law-of-sines", name:"Law of Sines", fields:[f("a","Side a"),f("A","Angle A"),f("b","Side b"),f("B","Angle B")], formula:"a/sin A = b/sin B", labels:{a:"Side a",b:"Side b"}, solve:{a:v=>n(v,"b")*Math.sin(n(v,"A")*Math.PI/180)/Math.sin(n(v,"B")*Math.PI/180),b:v=>n(v,"a")*Math.sin(n(v,"B")*Math.PI/180)/Math.sin(n(v,"A")*Math.PI/180),A:v=>Math.asin(n(v,"a")*Math.sin(n(v,"B")*Math.PI/180)/n(v,"b"))*180/Math.PI,B:v=>Math.asin(n(v,"b")*Math.sin(n(v,"A")*Math.PI/180)/n(v,"a"))*180/Math.PI} },
  { key:"law-of-cosines", name:"Law of Cosines", fields:[f("c","Side c"),f("a","Side a"),f("b","Side b"),f("C","Angle C")], formula:"c² = a²+b²−2ab cos C", labels:{c:"Side c"}, solve:{c:v=>Math.sqrt(n(v,"a")**2+n(v,"b")**2-2*n(v,"a")*n(v,"b")*Math.cos(n(v,"C")*Math.PI/180)),a:v=>n(v,"b")*Math.cos(n(v,"C")*Math.PI/180)+Math.sqrt(n(v,"c")**2-n(v,"b")**2*Math.sin(n(v,"C")*Math.PI/180)**2),b:v=>n(v,"a")*Math.cos(n(v,"C")*Math.PI/180)+Math.sqrt(n(v,"c")**2-n(v,"a")**2*Math.sin(n(v,"C")*Math.PI/180)**2),C:v=>Math.acos((n(v,"a")**2+n(v,"b")**2-n(v,"c")**2)/(2*n(v,"a")*n(v,"b")))*180/Math.PI} },
  { key:"arc-length", name:"Arc Length", fields:[f("s","Arc length"),f("r","Radius"),f("theta","Central angle" )], formula:"s = rθ", labels:{s:"Arc length"}, solve:{s:v=>n(v,"r")*n(v,"theta")*Math.PI/180,r:v=>n(v,"s")/(n(v,"theta")*Math.PI/180),theta:v=>n(v,"s")/n(v,"r")*180/Math.PI} },
  { key:"sector-area", name:"Sector Area", fields:[f("A","Sector area"),f("r","Radius"),f("theta","Central angle")], formula:"A = θr²/2", labels:{A:"Sector area"}, solve:{A:v=>n(v,"theta")*Math.PI/360*n(v,"r")**2,r:v=>Math.sqrt(n(v,"A")*360/(n(v,"theta")*Math.PI)),theta:v=>n(v,"A")*360/(Math.PI*n(v,"r")**2)} },
  { key:"rectangular-prism-volume", name:"Rectangular Prism Volume", fields:[f("V","Volume"),f("l","Length"),f("w","Width"),f("h","Height")], formula:"V = lwh", labels:{V:"Volume"}, solve:{V:v=>n(v,"l")*n(v,"w")*n(v,"h"),l:v=>n(v,"V")/(n(v,"w")*n(v,"h")),w:v=>n(v,"V")/(n(v,"l")*n(v,"h")),h:v=>n(v,"V")/(n(v,"l")*n(v,"w"))} },
  { key:"cylinder-surface-area", name:"Cylinder Surface Area", fields:[f("A","Surface area"),f("r","Radius"),f("h","Height")], formula:"A = 2πr² + 2πrh", labels:{A:"Surface area"}, solve:{A:v=>2*Math.PI*n(v,"r")**2+2*Math.PI*n(v,"r")*n(v,"h"),h:v=>(n(v,"A")-2*Math.PI*n(v,"r")**2)/(2*Math.PI*n(v,"r")),r:v=>{const h=n(v,"h"),A=n(v,"A"); return (-2*Math.PI*h+Math.sqrt((2*Math.PI*h)**2+8*Math.PI*A))/(4*Math.PI)}} },
  { key:"sphere-surface-area", name:"Sphere Surface Area", fields:[f("A","Surface area"),f("r","Radius")], formula:"A = 4πr²", labels:{A:"Surface area"}, solve:{A:v=>4*Math.PI*n(v,"r")**2,r:v=>Math.sqrt(n(v,"A")/(4*Math.PI))} },
  { key:"prism-surface-area", name:"Prism Surface Area", fields:[f("A","Surface area"),f("base","Base area"),f("perimeter","Base perimeter"),f("h","Height")], formula:"A = 2B + Ph", labels:{A:"Surface area"}, solve:{A:v=>2*n(v,"base")+n(v,"perimeter")*n(v,"h"),base:v=>(n(v,"A")-n(v,"perimeter")*n(v,"h"))/2,perimeter:v=>(n(v,"A")-2*n(v,"base"))/n(v,"h"),h:v=>(n(v,"A")-2*n(v,"base"))/n(v,"perimeter")} },
  { key:"rectangle-diagonal", name:"Rectangle Diagonal", fields:[f("d","Diagonal"),f("l","Length"),f("w","Width")], formula:"d = √(l²+w²)", labels:{d:"Diagonal"}, solve:{d:v=>Math.hypot(n(v,"l"),n(v,"w")),l:v=>Math.sqrt(n(v,"d")**2-n(v,"w")**2),w:v=>Math.sqrt(n(v,"d")**2-n(v,"l")**2)} },
  { key:"triangle-perimeter", name:"Triangle Perimeter", fields:[f("P","Perimeter"),f("a","Side a"),f("b","Side b"),f("c","Side c")], formula:"P = a+b+c", labels:{P:"Perimeter"}, solve:{P:v=>n(v,"a")+n(v,"b")+n(v,"c"),a:v=>n(v,"P")-n(v,"b")-n(v,"c"),b:v=>n(v,"P")-n(v,"a")-n(v,"c"),c:v=>n(v,"P")-n(v,"a")-n(v,"b")} },
  { key:"heron-area", name:"Heron's Formula", fields:[f("A","Area"),f("a","Side a"),f("b","Side b"),f("c","Side c")], formula:"A = √(s(s−a)(s−b)(s−c))", labels:{A:"Area"}, solve:{A:v=>{const a=n(v,"a"),b=n(v,"b"),c=n(v,"c"),s=(a+b+c)/2; return Math.sqrt(s*(s-a)*(s-b)*(s-c));}} },
  { key:"percent-error", name:"Percent Error", fields:[f("error","Percent error"),f("experimental","Experimental"),f("accepted","Accepted")], formula:"% error = |experimental−accepted|/accepted × 100", labels:{error:"Percent error"}, solve:{error:v=>Math.abs(n(v,"experimental")-n(v,"accepted"))/Math.abs(n(v,"accepted"))*100,experimental:v=>n(v,"accepted")*(1+n(v,"error")/100),accepted:v=>n(v,"experimental")/(1+n(v,"error")/100)} },
  { key:"relative-error", name:"Relative Error", fields:[f("error","Relative error"),f("absolute","Absolute error"),f("true","True value")], formula:"relative error = absolute/true", labels:{error:"Relative error"}, solve:{error:v=>Math.abs(n(v,"absolute")/n(v,"true")),absolute:v=>n(v,"error")*n(v,"true"),true:v=>n(v,"absolute")/n(v,"error")} },
  { key:"scientific-notation", name:"Scientific Notation", fields:[f("x","Number"),f("m","Mantissa"),f("e","Exponent")], formula:"x = m × 10^e", labels:{x:"Number"}, solve:{x:v=>n(v,"m")*10**n(v,"e"),m:v=>n(v,"x")/10**n(v,"e"),e:v=>Math.log10(Math.abs(n(v,"x")/n(v,"m")))} },
  { key:"log-product", name:"Logarithm Product Rule", fields:[f("L","Log result"),f("a","Base"),f("x","x"),f("y","y")], formula:"log_a(xy)=log_a(x)+log_a(y)", labels:{L:"Log result"}, solve:{L:v=>Math.log(n(v,"x")*n(v,"y"))/Math.log(n(v,"a"))} },
  { key:"exponential-growth", name:"Exponential Growth", fields:[f("A","Final amount"),f("P","Initial amount"),f("r","Growth rate"),f("t","Time")], formula:"A = Pe^(rt)", labels:{A:"Final amount"}, solve:{A:v=>n(v,"P")*Math.exp(n(v,"r")*n(v,"t")),P:v=>n(v,"A")/Math.exp(n(v,"r")*n(v,"t")),r:v=>Math.log(n(v,"A")/n(v,"P"))/n(v,"t"),t:v=>Math.log(n(v,"A")/n(v,"P"))/n(v,"r")} },
  { key:"doubling-time", name:"Doubling Time", fields:[f("t","Doubling time"),f("r","Growth rate")], formula:"t = ln(2)/r", labels:{t:"Doubling time"}, solve:{t:v=>Math.log(2)/n(v,"r"),r:v=>Math.log(2)/n(v,"t")} },
  { key:"arithmetic-mean", name:"Arithmetic Mean", fields:[f("mean","Mean"),f("sum","Sum"),f("n","Count")], formula:"mean = sum/n", labels:{mean:"Mean"}, solve:{mean:v=>n(v,"sum")/n(v,"n"),sum:v=>n(v,"mean")*n(v,"n"),n:v=>n(v,"sum")/n(v,"mean")} },
  { key:"geometric-mean", name:"Geometric Mean", fields:[f("mean","Geometric mean"),f("product","Product"),f("n","Count")], formula:"GM = product^(1/n)", labels:{mean:"Geometric mean"}, solve:{mean:v=>n(v,"product")**(1/n(v,"n")),product:v=>n(v,"mean")**n(v,"n"),n:v=>Math.log(n(v,"product"))/Math.log(n(v,"mean"))} },
  { key:"range-statistic", name:"Range Statistic", fields:[f("range","Range"),f("max","Maximum"),f("min","Minimum")], formula:"range = max−min", labels:{range:"Range"}, solve:{range:v=>n(v,"max")-n(v,"min"),max:v=>n(v,"range")+n(v,"min"),min:v=>n(v,"max")-n(v,"range")} },
  { key:"coefficient-variation", name:"Coefficient of Variation", fields:[f("cv","CV"),f("sd","Standard deviation"),f("mean","Mean")], formula:"CV = sd/mean × 100", labels:{cv:"CV %"}, solve:{cv:v=>n(v,"sd")/n(v,"mean")*100,sd:v=>n(v,"cv")/100*n(v,"mean"),mean:v=>n(v,"sd")/(n(v,"cv")/100)} },
  { key:"odds-probability", name:"Odds to Probability", fields:[f("p","Probability"),f("odds","Odds")], formula:"p = odds/(1+odds)", labels:{p:"Probability"}, solve:{p:v=>n(v,"odds")/(1+n(v,"odds")),odds:v=>n(v,"p")/(1-n(v,"p"))} },
  { key:"probability-complement", name:"Probability Complement", fields:[f("p","Probability"),f("q","Complement")], formula:"q = 1−p", labels:{q:"Complement"}, solve:{q:v=>1-n(v,"p"),p:v=>1-n(v,"q")} },
  { key:"permutation", name:"Permutation", fields:[f("P","Permutations"),f("n","Total items"),f("r","Selected items")], formula:"P(n,r)=n!/(n−r)!", labels:{P:"Permutations"}, solve:{P:v=>{let r=1;for(let i=0;i<Math.round(n(v,"r"));i++)r*=n(v,"n")-i;return r;}} },
  { key:"combination", name:"Combination", fields:[f("C","Combinations"),f("n","Total items"),f("r","Selected items")], formula:"C(n,r)=n!/(r!(n−r)!)", labels:{C:"Combinations"}, solve:{C:v=>{const N=Math.round(n(v,"n"));let R=Math.round(n(v,"r")); if(R>N) throw new Error("r cannot exceed n."); R=Math.min(R,N-R); let c=1;for(let i=1;i<=R;i++)c=c*(N-R+i)/i;return c;}} },
  { key:"simple-linear-regression", name:"Linear Prediction", fields:[f("y","Predicted y"),f("m","Slope"),f("x","x"),f("b","Intercept")], formula:"y = mx+b", labels:{y:"Predicted y"}, solve:{y:v=>n(v,"m")*n(v,"x")+n(v,"b"),m:v=>(n(v,"y")-n(v,"b"))/n(v,"x"),x:v=>(n(v,"y")-n(v,"b"))/n(v,"m"),b:v=>n(v,"y")-n(v,"m")*n(v,"x")} },
  { key:"vector-magnitude", name:"Vector Magnitude", fields:[f("mag","Magnitude"),f("x","x component"),f("y","y component")], formula:"|v| = √(x²+y²)", labels:{mag:"Magnitude"}, solve:{mag:v=>Math.hypot(n(v,"x"),n(v,"y")),x:v=>Math.sqrt(n(v,"mag")**2-n(v,"y")**2),y:v=>Math.sqrt(n(v,"mag")**2-n(v,"x")**2)} },
  { key:"vector-dot", name:"Vector Dot Product", fields:[f("dot","Dot product"),f("ax","aₓ"),f("ay","aᵧ"),f("bx","bₓ"),f("by","bᵧ")], formula:"a·b = axbx + ayby", labels:{dot:"Dot product"}, solve:{dot:v=>n(v,"ax")*n(v,"bx")+n(v,"ay")*n(v,"by")} },
  { key:"work-angle", name:"Work at an Angle", fields:[f("W","Work"),f("F","Force"),f("d","Distance"),f("theta","Angle")], formula:"W = Fd cosθ", labels:{W:"Work"}, solve:{W:v=>n(v,"F")*n(v,"d")*Math.cos(n(v,"theta")*Math.PI/180),F:v=>n(v,"W")/(n(v,"d")*Math.cos(n(v,"theta")*Math.PI/180)),d:v=>n(v,"W")/(n(v,"F")*Math.cos(n(v,"theta")*Math.PI/180))} },
  { key:"gravitational-force", name:"Gravitational Force", fields:[f("F","Force"),f("G","G"),f("m1","Mass 1"),f("m2","Mass 2"),f("r","Distance")], formula:"F = Gm₁m₂/r²", labels:{F:"Gravitational force"}, solve:{F:v=>n(v,"G")*n(v,"m1")*n(v,"m2")/n(v,"r")**2,m1:v=>n(v,"F")*n(v,"r")**2/(n(v,"G")*n(v,"m2")),m2:v=>n(v,"F")*n(v,"r")**2/(n(v,"G")*n(v,"m1")),r:v=>Math.sqrt(n(v,"G")*n(v,"m1")*n(v,"m2")/n(v,"F"))} },
  { key:"kinematic-displacement", name:"Kinematic Displacement", fields:[f("s","Displacement"),f("u","Initial velocity"),f("t","Time"),f("a","Acceleration")], formula:"s = ut + ½at²", labels:{s:"Displacement"}, solve:{s:v=>n(v,"u")*n(v,"t")+.5*n(v,"a")*n(v,"t")**2,u:v=>(n(v,"s")-.5*n(v,"a")*n(v,"t")**2)/n(v,"t"),a:v=>2*(n(v,"s")-n(v,"u")*n(v,"t"))/n(v,"t")**2,t:v=>{const u=n(v,"u"),a=n(v,"a"),s=n(v,"s");return (-u+Math.sqrt(u*u+2*a*s))/a;}} },
  { key:"kinematic-final-velocity", name:"Kinematic Final Velocity", fields:[f("v","Final velocity"),f("u","Initial velocity"),f("a","Acceleration"),f("s","Displacement")], formula:"v² = u² + 2as", labels:{v:"Final velocity"}, solve:{v:v=>Math.sqrt(n(v,"u")**2+2*n(v,"a")*n(v,"s")),u:v=>Math.sqrt(n(v,"v")**2-2*n(v,"a")*n(v,"s")),a:v=>(n(v,"v")**2-n(v,"u")**2)/(2*n(v,"s")),s:v=>(n(v,"v")**2-n(v,"u")**2)/(2*n(v,"a"))} },
  { key:"ideal-efficiency", name:"Energy Efficiency", fields:[f("eta","Efficiency"),f("out","Output energy"),f("in","Input energy")], formula:"η = output/input × 100%", labels:{eta:"Efficiency"}, solve:{eta:v=>n(v,"out")/n(v,"in")*100,out:v=>n(v,"eta")/100*n(v,"in"),in:v=>n(v,"out")/(n(v,"eta")/100)} },
  { key:"electric-resistance-series", name:"Series Resistance", fields:[f("R","Total resistance"),f("R1","R1"),f("R2","R2"),f("R3","R3")], formula:"R = R₁+R₂+R₃", labels:{R:"Total resistance"}, solve:{R:v=>n(v,"R1")+n(v,"R2")+n(v,"R3"),R1:v=>n(v,"R")-n(v,"R2")-n(v,"R3"),R2:v=>n(v,"R")-n(v,"R1")-n(v,"R3"),R3:v=>n(v,"R")-n(v,"R1")-n(v,"R2")} },
  { key:"electric-resistance-parallel", name:"Parallel Resistance", fields:[f("R","Equivalent resistance"),f("R1","R1"),f("R2","R2")], formula:"1/R = 1/R₁ + 1/R₂", labels:{R:"Equivalent resistance"}, solve:{R:v=>1/(1/n(v,"R1")+1/n(v,"R2")),R1:v=>1/(1/n(v,"R")-1/n(v,"R2")),R2:v=>1/(1/n(v,"R")-1/n(v,"R1"))} },
  { key:"electrical-energy", name:"Electrical Energy", fields:[f("E","Energy"),f("P","Power"),f("t","Time")], formula:"E = Pt", labels:{E:"Energy"}, solve:{E:v=>n(v,"P")*n(v,"t"),P:v=>n(v,"E")/n(v,"t"),t:v=>n(v,"E")/n(v,"P")} },
  { key:"heat-temperature-change", name:"Temperature Change from Heat", fields:[f("deltaT","Temperature change"),f("Q","Heat"),f("m","Mass"),f("c","Specific heat")], formula:"ΔT = Q/(mc)", labels:{deltaT:"Temperature change"}, solve:{deltaT:v=>n(v,"Q")/(n(v,"m")*n(v,"c")),Q:v=>n(v,"deltaT")*n(v,"m")*n(v,"c"),m:v=>n(v,"Q")/(n(v,"deltaT")*n(v,"c")),c:v=>n(v,"Q")/(n(v,"m")*n(v,"deltaT"))} },
  { key:"concentration-percent", name:"Percent Concentration", fields:[f("percent","Concentration %"),f("solute","Solute"),f("solution","Solution")], formula:"% = solute/solution × 100", labels:{percent:"Concentration %"}, solve:{percent:v=>n(v,"solute")/n(v,"solution")*100,solute:v=>n(v,"percent")/100*n(v,"solution"),solution:v=>n(v,"solute")/(n(v,"percent")/100)} },
  { key:"dilution", name:"Dilution Formula", fields:[f("C1","Initial concentration"),f("V1","Initial volume"),f("C2","Final concentration"),f("V2","Final volume")], formula:"C₁V₁ = C₂V₂", labels:{C1:"Initial concentration"}, solve:{C1:v=>n(v,"C2")*n(v,"V2")/n(v,"V1"),V1:v=>n(v,"C2")*n(v,"V2")/n(v,"C1"),C2:v=>n(v,"C1")*n(v,"V1")/n(v,"V2"),V2:v=>n(v,"C1")*n(v,"V1")/n(v,"C2")} },
  { key:"molarity-from-mass", name:"Molarity from Mass", fields:[f("M","Molarity"),f("m","Mass"),f("MM","Molar mass"),f("V","Volume")], formula:"M = m/(MM·V)", labels:{M:"Molarity"}, solve:{M:v=>n(v,"m")/(n(v,"MM")*n(v,"V")),m:v=>n(v,"M")*n(v,"MM")*n(v,"V"),MM:v=>n(v,"m")/(n(v,"M")*n(v,"V")),V:v=>n(v,"m")/(n(v,"M")*n(v,"MM"))} },
  { key:"gas-density", name:"Ideal Gas Density", fields:[f("rho","Density"),f("P","Pressure"),f("MM","Molar mass"),f("R","Gas constant"),f("T","Temperature")], formula:"ρ = PMM/(RT)", labels:{rho:"Density"}, solve:{rho:v=>n(v,"P")*n(v,"MM")/(n(v,"R")*n(v,"T")),P:v=>n(v,"rho")*n(v,"R")*n(v,"T")/n(v,"MM"),MM:v=>n(v,"rho")*n(v,"R")*n(v,"T")/n(v,"P"),T:v=>n(v,"P")*n(v,"MM")/(n(v,"rho")*n(v,"R"))} },

  { key:"derivative-power", name:"Power Rule Derivative", fields:[f("D","Derivative"),f("n","Exponent"),f("x","x")], formula:"d(xⁿ)/dx = n xⁿ⁻¹", labels:{D:"Derivative"}, solve:{D:v=>n(v,"n")*Math.pow(n(v,"x"),n(v,"n")-1)} },
  { key:"derivative-linear", name:"Linear Derivative", fields:[f("D","Derivative"),f("m","Slope"),f("x","x"),f("b","Intercept")], formula:"d(mx+b)/dx = m", labels:{D:"Derivative"}, solve:{D:v=>n(v,"m"),m:v=>n(v,"D")} },
  { key:"derivative-exponential", name:"Exponential Derivative", fields:[f("D","Derivative"),f("a","Base"),f("x","x")], formula:"d(aˣ)/dx = aˣ ln(a)", labels:{D:"Derivative"}, solve:{D:v=>Math.pow(n(v,"a"),n(v,"x"))*Math.log(n(v,"a"))} },
  { key:"derivative-natural-log", name:"Natural Log Derivative", fields:[f("D","Derivative"),f("x","x")], formula:"d(ln x)/dx = 1/x", labels:{D:"Derivative"}, solve:{D:v=>1/n(v,"x"),x:v=>1/n(v,"D")} },
  { key:"derivative-sine", name:"Sine Derivative", fields:[f("D","Derivative"),f("x","x")], formula:"d(sin x)/dx = cos x", labels:{D:"Derivative"}, solve:{D:v=>Math.cos(n(v,"x"))} },
  { key:"derivative-cosine", name:"Cosine Derivative", fields:[f("D","Derivative"),f("x","x")], formula:"d(cos x)/dx = −sin x", labels:{D:"Derivative"}, solve:{D:v=>-Math.sin(n(v,"x"))} },
  { key:"integral-power", name:"Power Rule Antiderivative", fields:[f("I","Antiderivative"),f("n","Exponent"),f("x","x")], formula:"∫xⁿdx = xⁿ⁺¹/(n+1)+C", labels:{I:"Antiderivative"}, solve:{I:v=>Math.pow(n(v,"x"),n(v,"n")+1)/(n(v,"n")+1)} },
  { key:"integral-linear", name:"Linear Antiderivative", fields:[f("I","Antiderivative"),f("m","Slope"),f("x","x"),f("b","Intercept")], formula:"∫(mx+b)dx = mx²/2 + bx + C", labels:{I:"Antiderivative"}, solve:{I:v=>n(v,"m")*n(v,"x")**2/2+n(v,"b")*n(v,"x")} },
  { key:"integral-exponential", name:"Exponential Antiderivative", fields:[f("I","Antiderivative"),f("a","Base"),f("x","x")], formula:"∫aˣdx = aˣ/ln(a)+C", labels:{I:"Antiderivative"}, solve:{I:v=>Math.pow(n(v,"a"),n(v,"x"))/Math.log(n(v,"a"))} },
  { key:"definite-integral-linear", name:"Definite Integral of Linear Function", fields:[f("I","Integral"),f("m","Slope"),f("b","Intercept"),f("a","Lower bound"),f("z","Upper bound")], formula:"∫ₐᶻ(mx+b)dx = m(z²−a²)/2 + b(z−a)", labels:{I:"Integral"}, solve:{I:v=>n(v,"m")*(n(v,"z")**2-n(v,"a")**2)/2+n(v,"b")*(n(v,"z")-n(v,"a"))} },
  { key:"trapezoidal-integral", name:"Trapezoidal Rule", fields:[f("I","Approximate integral"),f("h","Step width"),f("first","First value"),f("last","Last value"),f("middle","Sum of middle values")], formula:"I ≈ h[(first+last)/2 + middle]", labels:{I:"Approximate integral"}, solve:{I:v=>n(v,"h")*((n(v,"first")+n(v,"last"))/2+n(v,"middle"))} },
  { key:"average-value-function", name:"Average Value of a Function", fields:[f("avg","Average value"),f("I","Definite integral"),f("a","Lower bound"),f("b","Upper bound")], formula:"f̄ = I/(b−a)", labels:{avg:"Average value"}, solve:{avg:v=>n(v,"I")/(n(v,"b")-n(v,"a")),I:v=>n(v,"avg")*(n(v,"b")-n(v,"a"))} },
  { key:"annuity-future-value", name:"Future Value of Annuity", fields:[f("FV","Future value"),f("PMT","Payment"),f("r","Rate per period"),f("n","Number of periods")], formula:"FV = PMT[(1+r)ⁿ−1]/r", labels:{FV:"Future value"}, solve:{FV:v=>n(v,"PMT")*((1+n(v,"r"))**n(v,"n")-1)/n(v,"r"),PMT:v=>n(v,"FV")*n(v,"r")/((1+n(v,"r"))**n(v,"n")-1)} },
  { key:"annuity-present-value", name:"Present Value of Annuity", fields:[f("PV","Present value"),f("PMT","Payment"),f("r","Rate per period"),f("n","Number of periods")], formula:"PV = PMT[1−(1+r)⁻ⁿ]/r", labels:{PV:"Present value"}, solve:{PV:v=>n(v,"PMT")*(1-(1+n(v,"r"))**(-n(v,"n")))/n(v,"r"),PMT:v=>n(v,"PV")*n(v,"r")/(1-(1+n(v,"r"))**(-n(v,"n")))} },
  { key:"present-value", name:"Present Value", fields:[f("PV","Present value"),f("FV","Future value"),f("r","Rate per period"),f("n","Periods")], formula:"PV = FV/(1+r)ⁿ", labels:{PV:"Present value"}, solve:{PV:v=>n(v,"FV")/(1+n(v,"r"))**n(v,"n"),FV:v=>n(v,"PV")*(1+n(v,"r"))**n(v,"n"),r:v=>(n(v,"FV")/n(v,"PV"))**(1/n(v,"n"))-1,n:v=>Math.log(n(v,"FV")/n(v,"PV"))/Math.log(1+n(v,"r"))} },
  { key:"apy", name:"Annual Percentage Yield", fields:[f("APY","APY"),f("r","Nominal rate"),f("n","Compounds per year")], formula:"APY = (1+r/n)ⁿ−1", labels:{APY:"APY"}, solve:{APY:v=>(1+n(v,"r")/n(v,"n"))**n(v,"n")-1,r:v=>n(v,"n")*((1+n(v,"APY"))**(1/n(v,"n"))-1)} },
  { key:"sample-variance", name:"Sample Variance", fields:[f("s2","Sample variance"),f("sumSq","Sum of squared deviations"),f("n","Sample size")], formula:"s² = Σ(x−x̄)²/(n−1)", labels:{s2:"Sample variance"}, solve:{s2:v=>n(v,"sumSq")/(n(v,"n")-1),sumSq:v=>n(v,"s2")*(n(v,"n")-1),n:v=>n(v,"sumSq")/n(v,"s2")+1} },
  { key:"covariance", name:"Covariance", fields:[f("cov","Covariance"),f("sum","Sum of cross-deviations"),f("n","Count")], formula:"Cov(X,Y)=Σ[(x−x̄)(y−ȳ)]/n", labels:{cov:"Covariance"}, solve:{cov:v=>n(v,"sum")/n(v,"n"),sum:v=>n(v,"cov")*n(v,"n"),n:v=>n(v,"sum")/n(v,"cov")} },
  { key:"standard-score-from-raw", name:"Standard Score", fields:[f("z","Z-score"),f("x","Value"),f("mu","Mean"),f("sigma","Standard deviation")], formula:"z=(x−μ)/σ", labels:{z:"Z-score"}, solve:{z:v=>(n(v,"x")-n(v,"mu"))/n(v,"sigma"),x:v=>n(v,"mu")+n(v,"z")*n(v,"sigma"),mu:v=>n(v,"x")-n(v,"z")*n(v,"sigma"),sigma:v=>(n(v,"x")-n(v,"mu"))/n(v,"z")} },
  { key:"confidence-margin", name:"Margin of Error", fields:[f("E","Margin of error"),f("z","Critical value"),f("sigma","Standard deviation"),f("n","Sample size")], formula:"E = zσ/√n", labels:{E:"Margin of error"}, solve:{E:v=>n(v,"z")*n(v,"sigma")/Math.sqrt(n(v,"n")),z:v=>n(v,"E")*Math.sqrt(n(v,"n"))/n(v,"sigma"),sigma:v=>n(v,"E")*Math.sqrt(n(v,"n"))/n(v,"z"),n:v=>(n(v,"z")*n(v,"sigma")/n(v,"E"))**2} },

];

export function registerMathExerciseCalculators(calculators: Record<string, CalculatorDef>) {
  for (const spec of specs) {
    for (const [target, solve] of Object.entries(spec.solve)) {
      const key = `exercise-${spec.key}-${target}`;
      calculators[key] = {
        fields: spec.fields.filter((field) => field.name !== target),
        formula: `${spec.formula} · solve for ${target}`,
        compute: (v) => [out(spec.labels[target] ?? target, solve(v), true)],
      };
    }
  }
  registerExpansionCalculators(calculators);
}


type Expansion = { product: string[][]; sum: string[][]; ratio: string[][] };
const expansion = mathExpansion as Expansion;
const fieldFor = (name: string): Field => f(name, name.replace(/[-_]/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()));

function registerExpansionCalculators(calculators: Record<string, CalculatorDef>) {
  for (const [key, aLabel, bLabel, cLabel] of expansion.product) {
    const a = "a", b = "b", c = "c";
    for (const target of [a, b, c]) {
      const id = `exp-product-${key}-${target}`;
      calculators[id] = {
        fields: [fieldFor(a), fieldFor(b), fieldFor(c)].filter((x) => x.name !== target),
        formula: `${cLabel} = ${aLabel} × ${bLabel} · solve for ${target === a ? aLabel : target === b ? bLabel : cLabel}`,
        compute: (v) => {
          const av = target === a ? n(v, b) && 0 : n(v, a);
          const bv = target === b ? 0 : n(v, b);
          if (target === c) return [out(cLabel, av * bv)];
          if (target === a) return [out(aLabel, n(v, c) / n(v, b))];
          return [out(bLabel, n(v, c) / n(v, a))];
        },
      };
    }
  }
  for (const [key, aLabel, bLabel, cLabel] of expansion.sum) {
    for (const target of ["a", "b", "c"]) {
      const id = `exp-sum-${key}-${target}`;
      calculators[id] = {
        fields: [fieldFor("a"), fieldFor("b"), fieldFor("c")].filter((x) => x.name !== target),
        formula: `${cLabel} = ${aLabel} + ${bLabel} · solve for ${target}`,
        compute: (v) => target === "c" ? [out(cLabel, n(v,"a") + n(v,"b"))] : target === "a" ? [out(aLabel, n(v,"c") - n(v,"b"))] : [out(bLabel, n(v,"c") - n(v,"a"))],
      };
    }
  }
  for (const [key, aLabel, bLabel, cLabel] of expansion.ratio) {
    for (const target of ["a", "b", "c"]) {
      const id = `exp-ratio-${key}-${target}`;
      calculators[id] = {
        fields: [fieldFor("a"), fieldFor("b"), fieldFor("c")].filter((x) => x.name !== target),
        formula: `${cLabel} = ${aLabel} ÷ ${bLabel} · solve for ${target}`,
        compute: (v) => target === "c" ? [out(cLabel, n(v,"a") / n(v,"b"))] : target === "a" ? [out(aLabel, n(v,"c") * n(v,"b"))] : [out(bLabel, n(v,"a") / n(v,"c"))],
      };
    }
  }
}
