import { defineHandler } from "nitro/h3";
import { jsonResponse, optionsResponse } from "../../../../backend/http";
import { mkdtemp, writeFile, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawn } from "node:child_process";

const OPS = new Set([
  "document-comparison-tool","document-image-extractor","document-text-extractor","docx-comparison-tool","docx-compressor","docx-image-extractor","docx-merger","docx-metadata-tool","docx-page-extractor","docx-page-numbering-tool","docx-page-reorder-tool","docx-print-layout-helper","docx-screenshot-tool","docx-splitter","docx-text-extractor","docx-watermark-tool","image-image-extractor","image-page-extractor","image-page-numbering-tool","image-page-reorder-tool","image-splitter","image-text-extractor","ocr-tool","pdf-image-extractor","pdf-screenshot-tool","pdf-text-extractor","pdf-to-word","presentation-comparison-tool","presentation-compressor","presentation-image-extractor","presentation-merger","presentation-metadata-tool","presentation-page-extractor","presentation-page-numbering-tool","presentation-page-reorder-tool","presentation-print-layout-helper","presentation-screenshot-tool","presentation-splitter","presentation-text-extractor","presentation-watermark-tool","spreadsheet-comparison-tool","spreadsheet-compressor","spreadsheet-image-extractor","spreadsheet-merger","spreadsheet-metadata-tool","spreadsheet-page-extractor","spreadsheet-page-numbering-tool","spreadsheet-page-reorder-tool","spreadsheet-print-layout-helper","spreadsheet-screenshot-tool","spreadsheet-splitter","spreadsheet-text-extractor","spreadsheet-watermark-tool",
]);
function runPython(op:string,work:string,inputs:string[],params:Record<string,unknown>) { return new Promise<any>((resolve,reject)=>{const child=spawn("python3",["scripts/document/process.py",op,work,...inputs],{env:{...process.env,ENV_PARAMS:JSON.stringify(params)},stdio:["ignore","pipe","pipe"]});let out="",err="";child.stdout.on("data",c=>out+=c);child.stderr.on("data",c=>err+=c);child.on("close",code=>{try{const j=JSON.parse(out.trim().split(/\n/).at(-1)||"{}"); if(code===0&&j.path)return resolve(j); reject(new Error(j.error||err||"Document processor failed."));}catch{reject(new Error(err||"Document processor failed."));}});});}
export default defineHandler(async e=>{if(e.req.method==="OPTIONS")return optionsResponse();try{const f=await e.req.formData();const op=String(f.get("operation")||"");if(!OPS.has(op))return jsonResponse({error:"Unsupported document operation."},400);const params=JSON.parse(String(f.get("params")||"{}"));const files=f.getAll("files").filter((x):x is File=>x instanceof File);if(!files.length)return jsonResponse({error:"At least one document is required."},400);const work=await mkdtemp(join(tmpdir(),"env-doc-"));try{const paths:string[]=[];for(const [i,file] of files.entries()){const p=join(work,`${i}-${String(file.name).replace(/[^A-Za-z0-9._-]/g,"_")}`);await writeFile(p,Buffer.from(await file.arrayBuffer()));paths.push(p);}const result=await runPython(op,work,paths,params);const data=await readFile(result.path);return new Response(data,{headers:{"content-type":result.mime||"application/octet-stream","content-disposition":`attachment; filename="${String(f.get("outputName")||result.name).replace(/[^A-Za-z0-9._-]/g,"_")}"`,"cache-control":"no-store"}});}finally{await rm(work,{recursive:true,force:true}).catch(()=>{});}}catch(err){return jsonResponse({error:err instanceof Error?err.message:"Document processing failed."},400)}})
