import { defineHandler } from "nitro/h3";
import { PDFDocument, StandardFonts, degrees, rgb } from "pdf-lib";
import { optionsResponse, jsonResponse } from "../../../../backend/http";
function name(v:unknown,f:string){const x=String(v??f).replace(/[^A-Za-z0-9._-]/g,"_");return x||f}
function pages(raw:string,count:number){if(!raw.trim())return [...Array(count).keys()];const out:number[]=[];for(const token of raw.split(",").map(x=>x.trim()).filter(Boolean)){const m=token.match(/^(\d+)\s*-\s*(\d+)$/);if(m){let a=+m[1],b=+m[2],step=a<=b?1:-1;for(;true;a+=step){if(a>=1&&a<=count)out.push(a-1);if(a===b)break}}else{const n=+token;if(Number.isInteger(n)&&n>=1&&n<=count)out.push(n-1)}}return [...new Set(out)]}
async function formFiles(req:Request){const f=await req.formData();const files=f.getAll("files").filter((x):x is File=>x instanceof File);const one=f.get("file");if(one instanceof File)files.unshift(one);if(!files.length)throw new Error("At least one PDF or image file is required.");return {f,files}}
export default defineHandler(async e=>{if(e.req.method==="OPTIONS")return optionsResponse();try{const {f,files}=await formFiles(e.req);const op=String(f.get("operation")||"metadata");const params=JSON.parse(String(f.get("params")||"{}"));
if(op==="images-to-pdf"){const out=await PDFDocument.create();for(const file of files){const bytes=await file.arrayBuffer();const img=/png$/i.test(file.type)||/\.png$/i.test(file.name)?await out.embedPng(bytes):await out.embedJpg(bytes);const p=out.addPage([img.width,img.height]);p.drawImage(img,{x:0,y:0,width:img.width,height:img.height})}return new Response(await out.save(),{headers:{"content-type":"application/pdf","content-disposition":`attachment; filename="${name(f.get("outputName"),"images-to-pdf.pdf")}"`}})}
const source=await PDFDocument.load(await files[0].arrayBuffer());
if(op==="metadata"||op==="meta")return jsonResponse({pageCount:source.getPageCount(),title:source.getTitle()||"",author:source.getAuthor()||"",subject:source.getSubject()||"",keywords:source.getKeywords()||"",creator:source.getCreator()||"",producer:source.getProducer()||""});
if(op==="merge"){const out=await PDFDocument.create();for(const file of files){const d=await PDFDocument.load(await file.arrayBuffer());(await out.copyPages(d,d.getPageIndices())).forEach(p=>out.addPage(p))}return new Response(await out.save(),{headers:{"content-type":"application/pdf","content-disposition":`attachment; filename="${name(f.get("outputName"),"merged.pdf")}"`}})}
if(["extract","split","reorder"].includes(op)){const out=await PDFDocument.create();const ids=op==="reorder"?pages(String(params.pages||params.order||""),source.getPageCount()):pages(String(params.pages||params.range||""),source.getPageCount());(await out.copyPages(source,ids)).forEach(p=>out.addPage(p));return new Response(await out.save(),{headers:{"content-type":"application/pdf","content-disposition":`attachment; filename="${name(f.get("outputName"),"pages.pdf")}"`}})}
if(op==="rotate"){const a=Number(params.angle||90);source.getPages().forEach(p=>p.setRotation(degrees((p.getRotation().angle+a+360)%360)))}
if(op==="number"){const font=await source.embedFont(StandardFonts.Helvetica);source.getPages().forEach((p,i)=>{const s=p.getSize();p.drawText(String(i+1),{x:s.width-40,y:18,size:9,font,color:rgb(.3,.3,.3)})})}
if(op==="watermark"){const font=await source.embedFont(StandardFonts.HelveticaBold);const text=String(params.text||"enV");source.getPages().forEach(p=>{const s=p.getSize();p.drawText(text,{x:s.width/2-Math.min(160,text.length*3),y:s.height/2,size:Number(params.size||36),font,color:rgb(.45,.45,.45),opacity:Number(params.opacity||.18),rotate:degrees(Number(params.angle||30))})})}
return new Response(await source.save(),{headers:{"content-type":"application/pdf","content-disposition":`attachment; filename="${name(f.get("outputName"),"env-output.pdf")}"`}})
}catch(err){return jsonResponse({error:err instanceof Error?err.message:"PDF processing failed."},400)}})
