import { useState } from "react";
import { Button } from "@/components/ui/button";
import { ErrorBanner } from "@/components/tools/error-banner";
import { downloadBlob } from "@/lib/utils";

const ACCEPT = ".pdf,.docx,.pptx,.xlsx,.xls,.png,.jpg,.jpeg";
function label(id:string){return id.replace(/-/g," ").replace(/\b\w/g,c=>c.toUpperCase());}
export function DocumentToolsEngine({op}:{op:string}){
 const [files,setFiles]=useState<File[]>([]); const [pages,setPages]=useState("1"); const [text,setText]=useState("enV"); const [out,setOut]=useState<string>(""); const [err,setErr]=useState<string|null>(null); const [busy,setBusy]=useState(false);
 const run=async()=>{setBusy(true);setErr(null);setOut("");try{if(!files.length)throw new Error("Choose the document or file required by this tool.");const form=new FormData();for(const f of files)form.append("files",f,f.name);form.append("operation",op);form.append("params",JSON.stringify({pages,text}));form.append("outputName",`${op}-output`);const r=await fetch("/api/backend/documents",{method:"POST",body:form});if(!r.ok){let msg=`Document service returned HTTP ${r.status}.`;try{msg=(await r.json()).error||msg}catch{}throw new Error(msg)}const blob=await r.blob();const name=(r.headers.get("content-disposition")?.match(/filename="([^"]+)"/)?.[1])||`${op}-output`;downloadBlob(blob,name);setOut(`${label(op)} completed · ${(blob.size/1024).toFixed(1)} KB`)}catch(e){setErr(e instanceof Error?e.message:"Document operation failed.")}finally{setBusy(false)}};
 return <div className="space-y-4"><p className="text-sm text-subtle">Real document processing through the enV document backend. The selected file is processed for the requested operation and the resulting file is returned.</p><input type="file" multiple={/merger|comparison|splitter/.test(op)} accept={ACCEPT} onChange={e=>setFiles(Array.from(e.target.files??[]))}/>{/page-|splitter/.test(op)&&<label className="block text-sm">Pages / range<input className="mt-1 w-full rounded-md border bg-background px-3 py-2" value={pages} onChange={e=>setPages(e.target.value)} placeholder="1,3-5"/></label>}{/watermark/.test(op)&&<label className="block text-sm">Watermark text<input className="mt-1 w-full rounded-md border bg-background px-3 py-2" value={text} onChange={e=>setText(e.target.value)}/></label>}<ErrorBanner message={err}/><div className="flex gap-2"><Button onClick={run} disabled={busy}>{busy?"Processing…":`Run ${label(op)}`}</Button><Button variant="ghost" onClick={()=>{setFiles([]);setOut("");setErr(null)}}>Reset</Button></div>{out&&<div className="rounded-lg border bg-muted/20 p-4 text-sm">{out}</div>}</div>;
}
