import { useState } from "react";
import { Button } from "@/components/ui/button";
import { CodeResult } from "@/components/engines/result-panel";
import { ErrorBanner } from "@/components/tools/error-banner";

const commonPorts: Record<number,string> = {20:"FTP data",21:"FTP control",22:"SSH",23:"Telnet",25:"SMTP",53:"DNS",67:"DHCP server",68:"DHCP client",80:"HTTP",110:"POP3",123:"NTP",143:"IMAP",161:"SNMP",194:"IRC",389:"LDAP",443:"HTTPS",445:"SMB",465:"SMTPS",587:"SMTP submission",636:"LDAPS",993:"IMAPS",995:"POP3S",1433:"MS SQL Server",1521:"Oracle",2049:"NFS",2375:"Docker",2376:"Docker TLS",3000:"Development HTTP",3306:"MySQL",3389:"RDP",5432:"PostgreSQL",5672:"AMQP",6379:"Redis",8080:"HTTP alternate",8443:"HTTPS alternate",9200:"Elasticsearch"};

function parseIPv4(value:string){ const p=value.trim().split("."); if(p.length!==4||p.some(x=>!/^\d+$/.test(x)||Number(x)>255)) throw new Error("Enter a valid IPv4 address."); return p.map(Number); }
function ipToInt(p:number[]){ return (((p[0]*256+p[1])*256+p[2])*256+p[3])>>>0; }
function intToIp(n:number){ return [n>>>24,(n>>>16)&255,(n>>>8)&255,n&255].join("."); }
function prefixMask(prefix:number){ if(prefix<0||prefix>32) throw new Error("Prefix must be between 0 and 32."); return prefix===0?0:(0xffffffff << (32-prefix))>>>0; }
function bits(n:number){ return n.toString(2).padStart(32,"0").replace(/(.{8})/g,"$1 ").trim(); }
function parsePrefix(value:string){ const m=value.trim().match(/^(\d+(?:\.\d+){3})(?:\/(\d{1,2}))?$/); if(!m) throw new Error("Use an IPv4 address such as 192.168.1.10 or CIDR such as 192.168.1.10/24."); return {ip:parseIPv4(m[1]),prefix:m[2]===undefined?32:Number(m[2])}; }
function ipv4Result(ip:string,prefix:number){ const n=ipToInt(parseIPv4(ip)); const mask=prefixMask(prefix); const network=(n&mask)>>>0; const broadcast=(network|(~mask>>>0))>>>0; const total=2**(32-prefix); const usable=prefix>=31?total:Math.max(0,total-2); return {network:intToIp(network),broadcast:intToIp(broadcast),first:prefix>=31?intToIp(network):intToIp(network+1),last:prefix>=31?intToIp(broadcast):intToIp(broadcast-1),mask:intToIp(mask),wildcard:intToIp((~mask)>>>0),total,usable}; }
function ipv6Big(value:string){ let v=value.trim().toLowerCase(); if(v.includes("%")) v=v.split("%")[0]; if(v.includes(".")){ const idx=v.lastIndexOf(":"); const ip=v.slice(idx+1); const n=ipToInt(parseIPv4(ip)); v=v.slice(0,idx+1)+((n>>>16)&65535).toString(16)+":"+(n&65535).toString(16); }
 const halves=v.split("::"); if(halves.length>2) throw new Error("Invalid IPv6 address."); const left=halves[0]?halves[0].split(":").filter(Boolean):[]; const right=halves.length===2&&halves[1]?halves[1].split(":").filter(Boolean):[]; if(left.length+right.length>8) throw new Error("Invalid IPv6 address."); const fill=halves.length===2?8-left.length-right.length:0; const parts=[...left,...Array(fill).fill("0"),...right]; if(parts.length!==8||parts.some(x=>!/^[0-9a-f]{1,4}$/.test(x))) throw new Error("Invalid IPv6 address."); return parts.reduce((a,x)=>(a<<16n)+BigInt(parseInt(x,16)),0n); }
function ipv6Groups(n:bigint){ const out:string[]=[]; for(let i=7;i>=0;i--) out.push(((n>>BigInt(i*16))&65535n).toString(16)); return out; }
function compress6(n:bigint){ const g=ipv6Groups(n); let bestStart=-1,bestLen=0; for(let i=0;i<8;){ if(g[i]==="0"){let j=i;while(j<8&&g[j]==="0")j++; if(j-i>bestLen){bestStart=i;bestLen=j-i;} i=j;}else i++; } if(bestLen<2) return g.join(":"); const left=g.slice(0,bestStart).join(":"); const right=g.slice(bestStart+bestLen).join(":"); return `${left ? left+":" : ""}:${right ? right : ""}`; }
function ipv6Expanded(n:bigint){ return ipv6Groups(n).map(x=>x.padStart(4,"0")).join(":"); }
function field(label:string,value:string,set:(v:string)=>void,type="text",placeholder=""){ return <label className="flex flex-col gap-1.5"><span className="text-sm font-medium">{label}</span><input className="h-10 rounded-md border bg-background px-3" type={type} value={value} onChange={e=>set(e.target.value)} placeholder={placeholder}/></label>; }
function Result({text,filename="env-network.txt"}:{text:string;filename?:string}){ return <CodeResult code={text} filename={filename}/>; }

export function NetworkEngine({op}:{op:string}){
 const [a,setA]=useState("192.168.1.10/24"),[b,setB]=useState("24"),[out,setOut]=useState("")
 const [protocol,setProtocol]=useState("http"),[secure,setSecure]=useState("true"),[host,setHost]=useState("localhost"),[error,setError]=useState<string|null>(null);
 const [url,setUrl]=useState("https://example.com:443/path?utm_source=enV&x=1#section"),[name,setName]=useState(""),[value,setValue]=useState("");
 const [port,setPort]=useState("443"),[headers,setHeaders]=useState("Content-Type: application/json\nAuthorization: Bearer YOUR_TOKEN");
 const run=(fn:()=>string)=>{try{setError(null);setOut(fn());}catch(e){setOut("");setError(e instanceof Error?e.message:"Could not calculate.");}};
 const ipv4Ops=new Set(["ipv4-calculator","subnet-calculator","cidr-calculator","ipv4-binary","ipv4-decimal","ipv4-network-address","ipv4-broadcast-address","ipv4-host-range","ipv4-wildcard-mask","ipv4-mask-from-prefix","ipv4-prefix-from-mask","ipv4-host-count","ipv4-subnet-count","ipv4-split-subnets"]);
 const ipv6Ops=new Set(["ipv6-expand","ipv6-compress","ipv6-binary","ipv6-address-type","ipv6-subnet-calculator"]);
 if(ipv4Ops.has(op)) return <div className="space-y-4">{field("IPv4 / CIDR",a,setA,"text","192.168.1.10/24")}{field("Prefix or value",b,setB,"number","24")}<div className="flex gap-2"><Button onClick={()=>run(()=>{const p=parsePrefix(a);const pref=a.includes("/")?p.prefix:Number(b);const r=ipv4Result(intToIp(ipToInt(p.ip)),pref);if(op==="ipv4-calculator"||op==="subnet-calculator"||op==="cidr-calculator") return `Address: ${intToIp(ipToInt(p.ip))}/${pref}\nNetwork: ${r.network}\nBroadcast: ${r.broadcast}\nFirst usable: ${r.first}\nLast usable: ${r.last}\nSubnet mask: ${r.mask}\nWildcard mask: ${r.wildcard}\nTotal addresses: ${r.total}\nUsable hosts: ${r.usable}`; if(op==="ipv4-binary") return `Address: ${bits(ipToInt(p.ip))}\nMask: ${bits(prefixMask(pref))}`; if(op==="ipv4-decimal") return String(ipToInt(p.ip)); if(op==="ipv4-network-address") return r.network; if(op==="ipv4-broadcast-address") return r.broadcast; if(op==="ipv4-host-range") return `${r.first} – ${r.last}`; if(op==="ipv4-wildcard-mask") return r.wildcard; if(op==="ipv4-mask-from-prefix") return r.mask; if(op==="ipv4-prefix-from-mask"){const m=ipToInt(parseIPv4(a.replace(/\/.*$/,""))); const s=m.toString(2); if(s.includes("01")) throw new Error("Mask has non-contiguous 1 bits."); return `${s.split("1").length-1}`;} if(op==="ipv4-host-count") return String(r.usable); return `Addresses per /${pref}: ${r.total}\nUsable hosts: ${r.usable}`;})}>Calculate</Button></div><ErrorBanner message={error}/><Result text={out}/><p className="text-xs text-subtle">All calculations run locally. enV does not scan or contact the target address.</p></div>;
 if(ipv6Ops.has(op)) return <div className="space-y-4">{field("IPv6 address",a,setA,"text","2001:db8::1/64")}{field("Prefix",b,setB,"number","64")}<Button onClick={()=>run(()=>{const raw=a.split("/")[0];const n=ipv6Big(raw);const pref=Math.max(0,Math.min(128,Number(b)||64)); if(op==="ipv6-expand") return ipv6Expanded(n); if(op==="ipv6-compress") return compress6(n); if(op==="ipv6-binary") return n.toString(2).padStart(128,"0").replace(/(.{16})/g,"$1 "); if(op==="ipv6-address-type"){if(n===0n)return "Unspecified (::)"; if(n===1n)return "Loopback (::1)"; if((n>>118n)===0b11111100n)return "Unique local (fc00::/7)"; if((n>>120n)===0b11111111n)return "Multicast (ff00::/8)"; if((n>>96n)===0xffffn)return "IPv4-mapped IPv6"; return "Global/unicast or other address";} const hostBits=128-pref; const mask=hostBits===128?0n:((1n<<BigInt(pref))-1n)<<BigInt(hostBits); const network=n&mask; const last=network+((1n<<BigInt(hostBits))-1n); return `Network: ${compress6(network)}/${pref}\nFirst: ${compress6(network)}\nLast: ${compress6(last)}\nAddresses: 2^${hostBits}`;})}>Calculate</Button><ErrorBanner message={error}/><Result text={out}/></div>;
 if(op==="url-parser"||op==="url-query-parser"||op==="url-origin"||op==="url-path-analyzer") return <div className="space-y-4">{field("URL",url,setUrl,"url","https://example.com/path?x=1")}{field("Query name",name,setName)}{field("Query value",value,setValue)}<Button onClick={()=>run(()=>{const u=new URL(url);if(op==="url-parser") return `Protocol: ${u.protocol}\nUsername: ${u.username||"—"}\nHost: ${u.host}\nHostname: ${u.hostname}\nPort: ${u.port||"default"}\nPath: ${u.pathname}\nQuery: ${u.search||"—"}\nHash: ${u.hash||"—"}\nOrigin: ${u.origin}`;if(op==="url-origin")return u.origin;if(op==="url-path-analyzer")return `Path: ${u.pathname}\nSegments: ${u.pathname.split("/").filter(Boolean).length}\nLast segment: ${u.pathname.split("/").filter(Boolean).at(-1)||"—"}`;const entries=[...u.searchParams.entries()];return entries.length?entries.map(([k,v])=>`${k} = ${v}`).join("\n"):"No query parameters.";})}>Analyze</Button><ErrorBanner message={error}/><Result text={out}/></div>;
 if(op==="url-query-builder") return <div className="space-y-4">{field("Base URL",url,setUrl,"url","https://example.com/search")}{field("Parameter",name,setName)}{field("Value",value,setValue)}<Button onClick={()=>run(()=>{const u=new URL(url);u.searchParams.set(name,value);return u.toString();})}>Build URL</Button><ErrorBanner message={error}/><Result text={out}/></div>;
 if(op==="url-encode") return <div className="space-y-4">{field("Text",a,setA)}<Button onClick={()=>setOut(encodeURIComponent(a))}>Encode</Button><Result text={out}/></div>;
 if(op==="url-decode") return <div className="space-y-4">{field("Encoded text",a,setA)}<Button onClick={()=>run(()=>decodeURIComponent(a))}>Decode</Button><ErrorBanner message={error}/><Result text={out}/></div>;
 if(op==="port-lookup"||op==="port-reference") return <div className="space-y-4">{field("Port",port,setPort,"number","443")}{field("Service name (optional)",name,setName)}<Button onClick={()=>run(()=>{if(name.trim()){const q=name.toLowerCase();return Object.entries(commonPorts).filter(([,v])=>v.toLowerCase().includes(q)).map(([p,v])=>`${p}: ${v}`).join("\n")||"No match in the common-port reference.";}const p=Number(port);return commonPorts[p]?`${p}/TCP or UDP: ${commonPorts[p]}`:`${p}: not in the built-in common-port reference.`;})}>Lookup</Button><ErrorBanner message={error}/><Result text={out}/></div>;
 if(op==="http-status-reference") return <div className="grid gap-2 sm:grid-cols-2">{[[200,"OK"],[201,"Created"],[204,"No Content"],[301,"Moved Permanently"],[302,"Found"],[304,"Not Modified"],[400,"Bad Request"],[401,"Unauthorized"],[403,"Forbidden"],[404,"Not Found"],[405,"Method Not Allowed"],[409,"Conflict"],[429,"Too Many Requests"],[500,"Internal Server Error"],[502,"Bad Gateway"],[503,"Service Unavailable"],[504,"Gateway Timeout"]].map(([n,d])=><div key={n} className="rounded-lg border p-3"><b>{n}</b><span className="ml-2 text-subtle">{d}</span></div>)}</div>;
 if(op==="header-format"||op==="header-parser") return <div className="space-y-4">{field("Headers",headers,setHeaders)}<Button onClick={()=>run(()=>{const lines=headers.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const pairs=lines.map(x=>{const i=x.indexOf(":");return i>0?`${x.slice(0,i).trim()}: ${x.slice(i+1).trim()}`:x;});return op==="header-parser"?pairs.map(x=>{const i=x.indexOf(":");return i>0?`${x.slice(0,i)} → ${x.slice(i+1).trim()}`:x;}).join("\n"):pairs.join("\n");})}>Process</Button><ErrorBanner message={error}/><Result text={out}/></div>;
 if(op==="basic-auth-header") return <div className="space-y-4">{field("Username",name,setName)}{field("Password",value,setValue,"password")}<Button onClick={()=>setOut(`Basic ${btoa(`${name}:${value}`)}`)}>Generate</Button><Result text={out}/><p className="text-xs text-subtle">This only encodes credentials for the Authorization header; use HTTPS when sending credentials.</p></div>;
 if(op==="bearer-header") return <div className="space-y-4">{field("Token",a,setA)}<Button onClick={()=>setOut(`Bearer ${a}`)}>Generate</Button><Result text={out}/></div>;
 if(op==="connection-info") { const c=(navigator as Navigator & {connection?:{effectiveType?:string;downlink?:number;rtt?:number;saveData?:boolean}}).connection; return <div className="rounded-xl border p-4 space-y-2 text-sm"><div>Online: <b>{navigator.onLine?"Yes":"No"}</b></div><div>Effective type: <b>{c?.effectiveType||"Not exposed"}</b></div><div>Downlink estimate: <b>{c?.downlink!==undefined?`${c.downlink} Mb/s`:"Not exposed"}</b></div><div>RTT estimate: <b>{c?.rtt!==undefined?`${c.rtt} ms`:"Not exposed"}</b></div><div>Save-data: <b>{c?.saveData===undefined?"Not exposed":c.saveData?"On":"Off"}</b></div><p className="text-xs text-subtle">Values come from browser APIs and may be unavailable or approximate.</p></div>; }
 if(op==="http-method-reference") return <div className="grid gap-2">{[["GET","Retrieve a representation"],["POST","Submit data for processing"],["PUT","Replace a resource"],["PATCH","Partially modify a resource"],["DELETE","Remove a resource"],["HEAD","Headers without response body"],["OPTIONS","Discover communication options"],["CONNECT","Establish a tunnel"],["TRACE","Diagnostic loop-back method"]].map(([m,d])=><div key={m} className="rounded-lg border p-3"><b>{m}</b><span className="ml-2 text-subtle">{d}</span></div>)}</div>;
 if(op==="content-type-reference") return <div className="space-y-2">{["application/json","application/xml","application/x-www-form-urlencoded","multipart/form-data","text/plain","text/html","text/css","text/javascript","image/png","image/jpeg","image/webp","audio/mpeg","video/mp4"].map(x=><div key={x} className="rounded-lg border p-3 font-mono text-sm">{x}</div>)}</div>;
 if(op==="websocket-url-builder") return <div className="space-y-4">{field("Host",url,setUrl,"text","example.com")}{field("Path",name,setName,"text","/socket")}{field("Secure",secure,setSecure)}<Button onClick={()=>setOut(`${secure.toLowerCase()==="false"?"ws":"wss"}://${url.replace(/^https?:\/\//,"").replace(/\/$/,"")}${name.startsWith("/")?name:`/${name}`}`)}>Build</Button><Result text={out}/></div>;
 if(op==="localhost-url-builder") return <div className="space-y-4">{field("Port",port,setPort,"number","3000")}{field("Path",name,setName,"text","/")}{field("Protocol",protocol,setProtocol,"text","http")}{field("Host",host,setHost,"text","localhost") }<Button onClick={()=>setOut(`${protocol||"http"}://${host||"localhost"}:${port||"3000"}${name.startsWith("/")?name:`/${name}`}`)}>Build</Button><Result text={out}/></div>;
 return <div className="space-y-4"><p className="text-sm text-subtle">This network utility is available locally in your browser.</p></div>;
}
