import XCTest
@testable import enV

final class NativeTextEngineTests: XCTestCase {
    func testCatalogMappingIncludesAllFortyExactIDs() { XCTAssertEqual(NativeTextEngine.supportedToolIDs.count, 40); XCTAssertEqual(NativeTextEngine.operation(forToolID: "css-minifier-advanced"), "json-to-csv"); XCTAssertNil(NativeTextEngine.operation(forToolID: "future-tool")) }
    func testUnicodeCountersAndReversePreserveGraphemes() throws { let text="Hi 👩‍👩‍👧‍👦 世界!"; let s=NativeTextEngine.statistics(text); XCTAssertEqual(s.characters, text.unicodeScalars.count); XCTAssertEqual(NativeTextEngine.statistics("alpha, beta!!!").words, 2); XCTAssertEqual(try NativeTextEngine.run(toolID: "reverse-text", input: "A👩‍👩‍👧‍👦é").output, "é👩‍👩‍👧‍👦A") }
    func testBlankAndMalformedInputsMatchWebFallbacks() throws { XCTAssertEqual(try NativeTextEngine.run(toolID: "uppercase-converter", input: "").output, ""); XCTAssertThrowsError(try NativeTextEngine.run(toolID: "css-minifier-advanced", input: "{").output) { XCTAssertEqual(($0 as? NativeTextError)?.errorDescription, "Invalid JSON") } }
    func testConfigurableFindReplaceWrapListAndKeyword() throws { XCTAssertEqual(try NativeTextEngine.run(toolID: "find-and-replace", input: "Cat cat", options: ["find":"cat", "replace":"dog", "flags":"gi"]).output, "dog dog"); XCTAssertEqual(try NativeTextEngine.run(toolID: "wrap-text", input: "one two three", options: ["width":"8"]).output, "one two\nthree"); XCTAssertEqual(try NativeTextEngine.run(toolID: "list-generator", input: "a,b", options: ["style":"numbered"]).output, "1. a\n2. b"); XCTAssertTrue(try NativeTextEngine.run(toolID: "keyword-density-calculator", input: "Swift swift code", options: ["keyword":"swift"]).output.contains("density\t66.667%")) }
    func testConversionsFormattingAndDiff() throws { XCTAssertEqual(try NativeTextEngine.run(toolID: "css-minifier-advanced", input: "[{\"a\":1}]").output, "a\n1"); let xml = try NativeTextEngine.run(toolID: "json-to-xml", input: "{\"name\":\"Ada\"}").output; XCTAssertTrue(xml.contains("<name>") && xml.contains("Ada") && xml.contains("</name>")); let d=try NativeTextEngine.run(toolID: "text-diff", input: "same\nold", compare: "same\nnew"); XCTAssertEqual(d.added, 1); XCTAssertEqual(d.removed, 1); XCTAssertEqual(d.unchanged, 1) }
    func testJavaScriptMinifierPreservesCommentMarkersInsideStrings() throws { XCTAssertEqual(try NativeTextEngine.run(toolID: "javascript-minifier", input: "const url = 'https://a'; // trailing\n const x = 1;").output, "const url='https://a';const x=1;") }
    func testReadingSpeedOptionAndLimitsAreAccepted() throws { let r=try NativeTextEngine.run(toolID: "reading-time-calculator", input: "one two three", options: ["wpm":"60"]); XCTAssertEqual(r.statistics?.readingMinutes, 1); XCTAssertTrue(try NativeTextEngine.run(toolID: "word-counter", input: "a b", options: ["limit":"10"]).output.contains("Words: 2")) }
}
